# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .archive_agent_memory_response import ArchiveAgentMemoryResponse
    from .create_agent_memory_response import CreateAgentMemoryResponse
    from .get_agent_memory_response import GetAgentMemoryResponse
    from .list_agent_memories_response import ListAgentMemoriesResponse
    from .list_agent_memories_response_meta import ListAgentMemoriesResponseMeta
    from .supersede_agent_memory_response import SupersedeAgentMemoryResponse
_dynamic_imports: typing.Dict[str, str] = {
    "ArchiveAgentMemoryResponse": ".archive_agent_memory_response",
    "CreateAgentMemoryResponse": ".create_agent_memory_response",
    "GetAgentMemoryResponse": ".get_agent_memory_response",
    "ListAgentMemoriesResponse": ".list_agent_memories_response",
    "ListAgentMemoriesResponseMeta": ".list_agent_memories_response_meta",
    "SupersedeAgentMemoryResponse": ".supersede_agent_memory_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__}"
        )
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ArchiveAgentMemoryResponse",
    "CreateAgentMemoryResponse",
    "GetAgentMemoryResponse",
    "ListAgentMemoriesResponse",
    "ListAgentMemoriesResponseMeta",
    "SupersedeAgentMemoryResponse",
]
