# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.memory import Memory
from .list_agent_memories_response_meta import ListAgentMemoriesResponseMeta


class ListAgentMemoriesResponse(UniversalBaseModel):
    data: typing.Optional[typing.List[Memory]] = None
    meta: typing.Optional[ListAgentMemoriesResponseMeta] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
