"""Decode Band room failures for the ACP server boundary."""

from __future__ import annotations

from enum import StrEnum

from band_sdk_core import AgentFailure
from pydantic import JsonValue, TypeAdapter, ValidationError

from band.core.content import has_visible_content
from band.core.protocols import FailureMetadataKey
from band.core.redaction import redact_credentials, redact_credentials_deep
from band.core.types import PlatformMessage, metadata_to_dict

_JSON_VALUE = TypeAdapter(JsonValue)
_GENERIC_PEER_FAILURE = "Band peer reported a failure."


class ACPFailureProvider(StrEnum):
    """Providers for failures generated by the Band ACP server itself."""

    BAND = "band"


def decode_failure(msg: PlatformMessage) -> AgentFailure:
    """Invert the room failure shape from ``to_failure_event`` safely."""
    raw = metadata_to_dict(msg.metadata).get(FailureMetadataKey.FAILURE)
    if not isinstance(raw, dict):
        return _fallback_failure(msg)

    provider = raw.get("provider")
    message = raw.get("message")
    code = raw.get("code")
    if (
        not isinstance(provider, str)
        or not provider.strip()
        or not isinstance(message, str)
        or (code is not None and not isinstance(code, str))
    ):
        return _fallback_failure(msg)

    try:
        detail = _JSON_VALUE.validate_python(raw.get("detail"))
    except ValidationError:
        return _fallback_failure(msg)

    # ``to_failure_event`` keeps a blank ``message`` and puts the readable
    # fallback in the event content. That is still a valid Core failure.
    if not has_visible_content(message):
        message = msg.content.strip() or _GENERIC_PEER_FAILURE

    return AgentFailure(
        provider,
        redact_credentials(message),
        code=code,
        detail=redact_credentials_deep(detail),
    )


def _fallback_failure(msg: PlatformMessage) -> AgentFailure:
    """Use redacted event content when structured failure metadata is malformed."""
    return AgentFailure(
        ACPFailureProvider.BAND,
        redact_credentials(msg.content.strip() or _GENERIC_PEER_FAILURE),
    )


def prompt_timeout_failure(timeout_seconds: float) -> AgentFailure:
    """Stable Band-side failure when an ACP prompt waits too long."""
    if timeout_seconds == int(timeout_seconds):
        seconds_label = str(int(timeout_seconds))
    else:
        seconds_label = f"{timeout_seconds:g}"
    return AgentFailure(
        ACPFailureProvider.BAND,
        f"Prompt timed out after {seconds_label}s waiting for a Band peer reply.",
    )


def prompt_exception_failure(exc: BaseException) -> AgentFailure:
    """Map prompt setup or transport errors to a redacted Core failure."""
    message = str(exc).strip()
    if not message:
        message = type(exc).__name__
    return AgentFailure(ACPFailureProvider.BAND, redact_credentials(message))
