"""Decode Band room failures for the ACP server boundary."""

from __future__ import annotations

from enum import StrEnum

from band_sdk_core import AgentFailure
from pydantic import JsonValue, TypeAdapter, ValidationError

from band.core.protocols import FailureMetadataKey
from band.core.redaction import redact_credentials, redact_credentials_deep
from band.core.types import PlatformMessage, metadata_to_dict

_JSON_VALUE = TypeAdapter(JsonValue)


class ACPFailureProvider(StrEnum):
    """Providers for failures generated by the Band ACP server itself."""

    BAND = "band"


def decode_failure(msg: PlatformMessage) -> AgentFailure:
    """Invert the room failure shape from ``to_failure_event`` safely."""
    raw = metadata_to_dict(msg.metadata).get(FailureMetadataKey.FAILURE)
    if not isinstance(raw, dict):
        return _fallback_failure(msg)

    provider = raw.get("provider")
    message = raw.get("message")
    code = raw.get("code")
    if (
        not isinstance(provider, str)
        or not provider.strip()
        or not isinstance(message, str)
        or not message.strip()
        or (code is not None and not isinstance(code, str))
    ):
        return _fallback_failure(msg)

    try:
        detail = _JSON_VALUE.validate_python(raw.get("detail"))
    except ValidationError:
        return _fallback_failure(msg)

    return AgentFailure(
        provider,
        redact_credentials(message),
        code=code,
        detail=redact_credentials_deep(detail),
    )


def _fallback_failure(msg: PlatformMessage) -> AgentFailure:
    """Use redacted event content when structured failure metadata is malformed."""
    return AgentFailure(
        ACPFailureProvider.BAND,
        redact_credentials(msg.content.strip() or "Band peer reported a failure."),
    )
