# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawHumanApiPeersClient, RawHumanApiPeersClient
from .types.list_my_peers_request_type import ListMyPeersRequestType
from .types.list_my_peers_response import ListMyPeersResponse


class HumanApiPeersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawHumanApiPeersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawHumanApiPeersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawHumanApiPeersClient
        """
        return self._raw_client

    def list_my_peers(
        self,
        *,
        not_in_chat: typing.Optional[str] = None,
        type: typing.Optional[ListMyPeersRequestType] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMyPeersResponse:
        """
        Lists entities that you can interact with in chat rooms.

        Peers include:
        - Other users in your organization (registry)
        - Your contacts (users and agents)
        - Agents you own (registry)
        - Global agents (registry)

        Registry entries appear first, followed by contact-only entries.

        Use the `not_in_chat` parameter to filter out entities already in a specific chat room.
        Use the `type` parameter to filter by entity type (User or Agent).

        Parameters
        ----------
        not_in_chat : typing.Optional[str]
            Exclude entities already in this chat room

        type : typing.Optional[ListMyPeersRequestType]
            Filter by entity type

        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMyPeersResponse
            Peers list

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_peers.list_my_peers(
            not_in_chat="daca00d0-eb6b-4db1-8201-c46015c93d04",
            type="User",
            page=1,
            page_size=1,
        )
        """
        _response = self._raw_client.list_my_peers(
            not_in_chat=not_in_chat,
            type=type,
            page=page,
            page_size=page_size,
            request_options=request_options,
        )
        return _response.data


class AsyncHumanApiPeersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawHumanApiPeersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawHumanApiPeersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawHumanApiPeersClient
        """
        return self._raw_client

    async def list_my_peers(
        self,
        *,
        not_in_chat: typing.Optional[str] = None,
        type: typing.Optional[ListMyPeersRequestType] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMyPeersResponse:
        """
        Lists entities that you can interact with in chat rooms.

        Peers include:
        - Other users in your organization (registry)
        - Your contacts (users and agents)
        - Agents you own (registry)
        - Global agents (registry)

        Registry entries appear first, followed by contact-only entries.

        Use the `not_in_chat` parameter to filter out entities already in a specific chat room.
        Use the `type` parameter to filter by entity type (User or Agent).

        Parameters
        ----------
        not_in_chat : typing.Optional[str]
            Exclude entities already in this chat room

        type : typing.Optional[ListMyPeersRequestType]
            Filter by entity type

        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMyPeersResponse
            Peers list

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_peers.list_my_peers(
                not_in_chat="daca00d0-eb6b-4db1-8201-c46015c93d04",
                type="User",
                page=1,
                page_size=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_my_peers(
            not_in_chat=not_in_chat,
            type=type,
            page=page,
            page_size=page_size,
            request_options=request_options,
        )
        return _response.data
