# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.error import Error
from ..types.memory_create_request import MemoryCreateRequest
from .types.archive_agent_memory_response import ArchiveAgentMemoryResponse
from .types.create_agent_memory_response import CreateAgentMemoryResponse
from .types.get_agent_memory_response import GetAgentMemoryResponse
from .types.list_agent_memories_response import ListAgentMemoriesResponse
from .types.supersede_agent_memory_response import SupersedeAgentMemoryResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawAgentApiMemoriesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def supersede_agent_memory(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SupersedeAgentMemoryResponse]:
        """
        Marks a memory as superseded (soft delete). Use when information is outdated or incorrect.
        The memory remains for audit trail but won't appear in normal queries.

        Only the source agent can supersede.

        Parameters
        ----------
        id : str
            Memory ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SupersedeAgentMemoryResponse]
            Superseded Memory
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/agent/memories/{jsonable_encoder(id)}/supersede",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SupersedeAgentMemoryResponse,
                    parse_obj_as(
                        type_=SupersedeAgentMemoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )

    def archive_agent_memory(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ArchiveAgentMemoryResponse]:
        """
        Archives a memory (hides but preserves). Use when memory is valid but not currently needed.
        Archived memories can be restored later by humans.

        Only the source agent can archive.

        Parameters
        ----------
        id : str
            Memory ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ArchiveAgentMemoryResponse]
            Archived Memory
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/agent/memories/{jsonable_encoder(id)}/archive",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ArchiveAgentMemoryResponse,
                    parse_obj_as(
                        type_=ArchiveAgentMemoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )

    def get_agent_memory(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GetAgentMemoryResponse]:
        """
        Retrieves a specific memory by ID if accessible to the agent.

        Parameters
        ----------
        id : str
            Memory ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetAgentMemoryResponse]
            Memory
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/agent/memories/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetAgentMemoryResponse,
                    parse_obj_as(
                        type_=GetAgentMemoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )

    def list_agent_memories(
        self,
        *,
        subject_id: typing.Optional[str] = None,
        scope: typing.Optional[str] = None,
        system: typing.Optional[str] = None,
        type: typing.Optional[str] = None,
        segment: typing.Optional[str] = None,
        content_query: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        status: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListAgentMemoriesResponse]:
        """
        Lists memories accessible to the agent. By default returns:
        - Memories about the specified subject (cross-agent sharing)
        - Organization-wide shared memories

        Use `scope` parameter to filter by visibility.
        Use `content_query` for full-text search across memory content.

        Parameters
        ----------
        subject_id : typing.Optional[str]
            Filter by subject UUID (required for subject-scoped queries)

        scope : typing.Optional[str]
            Filter by scope: subject, organization, or all

        system : typing.Optional[str]
            Filter by memory system

        type : typing.Optional[str]
            Filter by memory type

        segment : typing.Optional[str]
            Filter by segment

        content_query : typing.Optional[str]
            Full-text search query

        page_size : typing.Optional[int]
            Number of results per page (max 50)

        status : typing.Optional[str]
            Filter by status: active, superseded, archived, or all

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListAgentMemoriesResponse]
            Memories
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/agent/memories",
            method="GET",
            params={
                "subject_id": subject_id,
                "scope": scope,
                "system": system,
                "type": type,
                "segment": segment,
                "content_query": content_query,
                "page_size": page_size,
                "status": status,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListAgentMemoriesResponse,
                    parse_obj_as(
                        type_=ListAgentMemoriesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )

    def create_agent_memory(
        self,
        *,
        memory: MemoryCreateRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateAgentMemoryResponse]:
        """
        Stores a new memory entry. The memory will be:
        - Associated with the authenticated agent as the source
        - Scoped to the subject (for cross-agent sharing) or organization (for shared knowledge)

        For subject-scoped memories, provide a `subject_id` to associate the memory with a specific user or agent.
        For organization-scoped memories, omit `subject_id` - the memory will be visible to all agents in the org.

        Parameters
        ----------
        memory : MemoryCreateRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateAgentMemoryResponse]
            Created Memory
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/agent/memories",
            method="POST",
            json={
                "memory": convert_and_respect_annotation_metadata(
                    object_=memory, annotation=MemoryCreateRequest, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateAgentMemoryResponse,
                    parse_obj_as(
                        type_=CreateAgentMemoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )


class AsyncRawAgentApiMemoriesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def supersede_agent_memory(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SupersedeAgentMemoryResponse]:
        """
        Marks a memory as superseded (soft delete). Use when information is outdated or incorrect.
        The memory remains for audit trail but won't appear in normal queries.

        Only the source agent can supersede.

        Parameters
        ----------
        id : str
            Memory ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SupersedeAgentMemoryResponse]
            Superseded Memory
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/agent/memories/{jsonable_encoder(id)}/supersede",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SupersedeAgentMemoryResponse,
                    parse_obj_as(
                        type_=SupersedeAgentMemoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )

    async def archive_agent_memory(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ArchiveAgentMemoryResponse]:
        """
        Archives a memory (hides but preserves). Use when memory is valid but not currently needed.
        Archived memories can be restored later by humans.

        Only the source agent can archive.

        Parameters
        ----------
        id : str
            Memory ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ArchiveAgentMemoryResponse]
            Archived Memory
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/agent/memories/{jsonable_encoder(id)}/archive",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ArchiveAgentMemoryResponse,
                    parse_obj_as(
                        type_=ArchiveAgentMemoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )

    async def get_agent_memory(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GetAgentMemoryResponse]:
        """
        Retrieves a specific memory by ID if accessible to the agent.

        Parameters
        ----------
        id : str
            Memory ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetAgentMemoryResponse]
            Memory
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/agent/memories/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetAgentMemoryResponse,
                    parse_obj_as(
                        type_=GetAgentMemoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )

    async def list_agent_memories(
        self,
        *,
        subject_id: typing.Optional[str] = None,
        scope: typing.Optional[str] = None,
        system: typing.Optional[str] = None,
        type: typing.Optional[str] = None,
        segment: typing.Optional[str] = None,
        content_query: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        status: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListAgentMemoriesResponse]:
        """
        Lists memories accessible to the agent. By default returns:
        - Memories about the specified subject (cross-agent sharing)
        - Organization-wide shared memories

        Use `scope` parameter to filter by visibility.
        Use `content_query` for full-text search across memory content.

        Parameters
        ----------
        subject_id : typing.Optional[str]
            Filter by subject UUID (required for subject-scoped queries)

        scope : typing.Optional[str]
            Filter by scope: subject, organization, or all

        system : typing.Optional[str]
            Filter by memory system

        type : typing.Optional[str]
            Filter by memory type

        segment : typing.Optional[str]
            Filter by segment

        content_query : typing.Optional[str]
            Full-text search query

        page_size : typing.Optional[int]
            Number of results per page (max 50)

        status : typing.Optional[str]
            Filter by status: active, superseded, archived, or all

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListAgentMemoriesResponse]
            Memories
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/agent/memories",
            method="GET",
            params={
                "subject_id": subject_id,
                "scope": scope,
                "system": system,
                "type": type,
                "segment": segment,
                "content_query": content_query,
                "page_size": page_size,
                "status": status,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListAgentMemoriesResponse,
                    parse_obj_as(
                        type_=ListAgentMemoriesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )

    async def create_agent_memory(
        self,
        *,
        memory: MemoryCreateRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateAgentMemoryResponse]:
        """
        Stores a new memory entry. The memory will be:
        - Associated with the authenticated agent as the source
        - Scoped to the subject (for cross-agent sharing) or organization (for shared knowledge)

        For subject-scoped memories, provide a `subject_id` to associate the memory with a specific user or agent.
        For organization-scoped memories, omit `subject_id` - the memory will be visible to all agents in the org.

        Parameters
        ----------
        memory : MemoryCreateRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateAgentMemoryResponse]
            Created Memory
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/agent/memories",
            method="POST",
            json={
                "memory": convert_and_respect_annotation_metadata(
                    object_=memory, annotation=MemoryCreateRequest, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateAgentMemoryResponse,
                    parse_obj_as(
                        type_=CreateAgentMemoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )
