# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .approve_contact_request_response import ApproveContactRequestResponse
    from .cancel_contact_request_response import CancelContactRequestResponse
    from .create_contact_request_request_contact_request import (
        CreateContactRequestRequestContactRequest,
    )
    from .create_contact_request_response import CreateContactRequestResponse
    from .list_my_contacts_response import ListMyContactsResponse
    from .list_my_contacts_response_metadata import ListMyContactsResponseMetadata
    from .list_received_contact_requests_response import (
        ListReceivedContactRequestsResponse,
    )
    from .list_received_contact_requests_response_metadata import (
        ListReceivedContactRequestsResponseMetadata,
    )
    from .list_sent_contact_requests_request_status import (
        ListSentContactRequestsRequestStatus,
    )
    from .list_sent_contact_requests_response import ListSentContactRequestsResponse
    from .list_sent_contact_requests_response_metadata import (
        ListSentContactRequestsResponseMetadata,
    )
    from .reject_contact_request_response import RejectContactRequestResponse
    from .remove_my_contact_response import RemoveMyContactResponse
    from .remove_my_contact_response_data import RemoveMyContactResponseData
    from .resolve_handle_response import ResolveHandleResponse
_dynamic_imports: typing.Dict[str, str] = {
    "ApproveContactRequestResponse": ".approve_contact_request_response",
    "CancelContactRequestResponse": ".cancel_contact_request_response",
    "CreateContactRequestRequestContactRequest": ".create_contact_request_request_contact_request",
    "CreateContactRequestResponse": ".create_contact_request_response",
    "ListMyContactsResponse": ".list_my_contacts_response",
    "ListMyContactsResponseMetadata": ".list_my_contacts_response_metadata",
    "ListReceivedContactRequestsResponse": ".list_received_contact_requests_response",
    "ListReceivedContactRequestsResponseMetadata": ".list_received_contact_requests_response_metadata",
    "ListSentContactRequestsRequestStatus": ".list_sent_contact_requests_request_status",
    "ListSentContactRequestsResponse": ".list_sent_contact_requests_response",
    "ListSentContactRequestsResponseMetadata": ".list_sent_contact_requests_response_metadata",
    "RejectContactRequestResponse": ".reject_contact_request_response",
    "RemoveMyContactResponse": ".remove_my_contact_response",
    "RemoveMyContactResponseData": ".remove_my_contact_response_data",
    "ResolveHandleResponse": ".resolve_handle_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__}"
        )
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ApproveContactRequestResponse",
    "CancelContactRequestResponse",
    "CreateContactRequestRequestContactRequest",
    "CreateContactRequestResponse",
    "ListMyContactsResponse",
    "ListMyContactsResponseMetadata",
    "ListReceivedContactRequestsResponse",
    "ListReceivedContactRequestsResponseMetadata",
    "ListSentContactRequestsRequestStatus",
    "ListSentContactRequestsResponse",
    "ListSentContactRequestsResponseMetadata",
    "RejectContactRequestResponse",
    "RemoveMyContactResponse",
    "RemoveMyContactResponseData",
    "ResolveHandleResponse",
]
