# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreateContactRequestRequestContactRequest(UniversalBaseModel):
    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional message to include with the request
    """

    recipient_handle: str = pydantic.Field()
    """
    Handle of the user to add (with or without @ prefix)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
