# This file was auto-generated by Fern from our API Definition.

import typing

ListSentContactRequestsRequestStatus = typing.Union[
    typing.Literal["all", "pending", "approved", "rejected", "cancelled"], typing.Any
]
