# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .delete_my_agent_response import DeleteMyAgentResponse
    from .delete_my_agent_response_data import DeleteMyAgentResponseData
    from .list_my_agents_response import ListMyAgentsResponse
    from .list_my_agents_response_metadata import ListMyAgentsResponseMetadata
    from .register_my_agent_response import RegisterMyAgentResponse
    from .register_my_agent_response_data import RegisterMyAgentResponseData
    from .register_my_agent_response_data_agent import RegisterMyAgentResponseDataAgent
    from .register_my_agent_response_data_credentials import (
        RegisterMyAgentResponseDataCredentials,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "DeleteMyAgentResponse": ".delete_my_agent_response",
    "DeleteMyAgentResponseData": ".delete_my_agent_response_data",
    "ListMyAgentsResponse": ".list_my_agents_response",
    "ListMyAgentsResponseMetadata": ".list_my_agents_response_metadata",
    "RegisterMyAgentResponse": ".register_my_agent_response",
    "RegisterMyAgentResponseData": ".register_my_agent_response_data",
    "RegisterMyAgentResponseDataAgent": ".register_my_agent_response_data_agent",
    "RegisterMyAgentResponseDataCredentials": ".register_my_agent_response_data_credentials",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__}"
        )
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "DeleteMyAgentResponse",
    "DeleteMyAgentResponseData",
    "ListMyAgentsResponse",
    "ListMyAgentsResponseMetadata",
    "RegisterMyAgentResponse",
    "RegisterMyAgentResponseData",
    "RegisterMyAgentResponseDataAgent",
    "RegisterMyAgentResponseDataCredentials",
]
