# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.agent_register_request import AgentRegisterRequest
from .raw_client import AsyncRawHumanApiAgentsClient, RawHumanApiAgentsClient
from .types.delete_my_agent_response import DeleteMyAgentResponse
from .types.list_my_agents_response import ListMyAgentsResponse
from .types.register_my_agent_response import RegisterMyAgentResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class HumanApiAgentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawHumanApiAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawHumanApiAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawHumanApiAgentsClient
        """
        return self._raw_client

    def register_my_agent(
        self,
        *,
        agent: AgentRegisterRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RegisterMyAgentResponse:
        """
        Registers a new external agent and returns its API key.

        External agents run their own reasoning loop and connect to the platform
        to participate in chat rooms and execute tasks.

        **Important**: The API key is only shown once - store it securely.

        Parameters
        ----------
        agent : AgentRegisterRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RegisterMyAgentResponse
            Registered Agent

        Examples
        --------
        from band_rest import AgentRegisterRequest, RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_agents.register_my_agent(
            agent=AgentRegisterRequest(
                description="description",
                name="name",
            ),
        )
        """
        _response = self._raw_client.register_my_agent(
            agent=agent, request_options=request_options
        )
        return _response.data

    def list_my_agents(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMyAgentsResponse:
        """
        Returns a paginated list of agents that you own.

        This includes both platform agents and external agents you have registered.
        Global agents owned by you are also included.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMyAgentsResponse
            Your Agents

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_agents.list_my_agents(
            page=1,
            page_size=1,
        )
        """
        _response = self._raw_client.list_my_agents(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    def delete_my_agent(
        self,
        id: str,
        *,
        force: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteMyAgentResponse:
        """
        Deletes an agent that you own.

        **Default behavior**: Returns 422 if agent has execution history.
        This protects audit trails and task history.

        **Force deletion** (`?force=true`): Deletes all execution history first,
        then deletes the agent. Use with caution - this is irreversible.

        Deletion will:
        - Revoke the agent's API key
        - Remove the agent from all chat rooms (soft delete)
        - Delete associated memories and tool configurations
        - With `force=true`: Delete all execution history

        Parameters
        ----------
        id : str
            Agent ID

        force : typing.Optional[bool]
            Force deletion including all execution history

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteMyAgentResponse
            Agent Deleted

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_agents.delete_my_agent(
            id="550e8400-e29b-41d4-a716-446655440000",
            force=True,
        )
        """
        _response = self._raw_client.delete_my_agent(
            id, force=force, request_options=request_options
        )
        return _response.data


class AsyncHumanApiAgentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawHumanApiAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawHumanApiAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawHumanApiAgentsClient
        """
        return self._raw_client

    async def register_my_agent(
        self,
        *,
        agent: AgentRegisterRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RegisterMyAgentResponse:
        """
        Registers a new external agent and returns its API key.

        External agents run their own reasoning loop and connect to the platform
        to participate in chat rooms and execute tasks.

        **Important**: The API key is only shown once - store it securely.

        Parameters
        ----------
        agent : AgentRegisterRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RegisterMyAgentResponse
            Registered Agent

        Examples
        --------
        import asyncio

        from band_rest import AgentRegisterRequest, AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_agents.register_my_agent(
                agent=AgentRegisterRequest(
                    description="description",
                    name="name",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.register_my_agent(
            agent=agent, request_options=request_options
        )
        return _response.data

    async def list_my_agents(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMyAgentsResponse:
        """
        Returns a paginated list of agents that you own.

        This includes both platform agents and external agents you have registered.
        Global agents owned by you are also included.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMyAgentsResponse
            Your Agents

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_agents.list_my_agents(
                page=1,
                page_size=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_my_agents(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def delete_my_agent(
        self,
        id: str,
        *,
        force: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteMyAgentResponse:
        """
        Deletes an agent that you own.

        **Default behavior**: Returns 422 if agent has execution history.
        This protects audit trails and task history.

        **Force deletion** (`?force=true`): Deletes all execution history first,
        then deletes the agent. Use with caution - this is irreversible.

        Deletion will:
        - Revoke the agent's API key
        - Remove the agent from all chat rooms (soft delete)
        - Delete associated memories and tool configurations
        - With `force=true`: Delete all execution history

        Parameters
        ----------
        id : str
            Agent ID

        force : typing.Optional[bool]
            Force deletion including all execution history

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteMyAgentResponse
            Agent Deleted

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_agents.delete_my_agent(
                id="550e8400-e29b-41d4-a716-446655440000",
                force=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_my_agent(
            id, force=force, request_options=request_options
        )
        return _response.data
