# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.error import Error
from ..types.participant_request import ParticipantRequest
from .types.add_my_chat_participant_response import AddMyChatParticipantResponse
from .types.list_my_chat_participants_request_participant_type import (
    ListMyChatParticipantsRequestParticipantType,
)
from .types.list_my_chat_participants_response import ListMyChatParticipantsResponse
from .types.remove_my_chat_participant_response import RemoveMyChatParticipantResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawHumanApiParticipantsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def remove_my_chat_participant(
        self,
        chat_id: str,
        id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[RemoveMyChatParticipantResponse]:
        """
        Removes a participant from a chat room where you have permission to remove participants.

        Requires owner or admin role in the chat room.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Participant ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RemoveMyChatParticipantResponse]
            Participant Removed
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/me/chats/{jsonable_encoder(chat_id)}/participants/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RemoveMyChatParticipantResponse,
                    parse_obj_as(
                        type_=RemoveMyChatParticipantResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )

    def list_my_chat_participants(
        self,
        chat_id: str,
        *,
        participant_type: typing.Optional[
            ListMyChatParticipantsRequestParticipantType
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListMyChatParticipantsResponse]:
        """
        Returns a list of participants in a chat room where you are a participant.

        Returns 404 if the chat room doesn't exist or you're not a participant
        (security-first: doesn't leak room existence).

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant_type : typing.Optional[ListMyChatParticipantsRequestParticipantType]
            Filter by participant type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListMyChatParticipantsResponse]
            Chat Room Participants
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/me/chats/{jsonable_encoder(chat_id)}/participants",
            method="GET",
            params={
                "participant_type": participant_type,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListMyChatParticipantsResponse,
                    parse_obj_as(
                        type_=ListMyChatParticipantsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )

    def add_my_chat_participant(
        self,
        chat_id: str,
        *,
        participant: ParticipantRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AddMyChatParticipantResponse]:
        """
        Adds a new participant to a chat room where you have permission to add participants.

        You can add:
        - Your own agents
        - Global agents

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant : ParticipantRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AddMyChatParticipantResponse]
            Participant Added
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/me/chats/{jsonable_encoder(chat_id)}/participants",
            method="POST",
            json={
                "participant": convert_and_respect_annotation_metadata(
                    object_=participant,
                    annotation=ParticipantRequest,
                    direction="write",
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AddMyChatParticipantResponse,
                    parse_obj_as(
                        type_=AddMyChatParticipantResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )


class AsyncRawHumanApiParticipantsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def remove_my_chat_participant(
        self,
        chat_id: str,
        id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[RemoveMyChatParticipantResponse]:
        """
        Removes a participant from a chat room where you have permission to remove participants.

        Requires owner or admin role in the chat room.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Participant ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RemoveMyChatParticipantResponse]
            Participant Removed
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/me/chats/{jsonable_encoder(chat_id)}/participants/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RemoveMyChatParticipantResponse,
                    parse_obj_as(
                        type_=RemoveMyChatParticipantResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )

    async def list_my_chat_participants(
        self,
        chat_id: str,
        *,
        participant_type: typing.Optional[
            ListMyChatParticipantsRequestParticipantType
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListMyChatParticipantsResponse]:
        """
        Returns a list of participants in a chat room where you are a participant.

        Returns 404 if the chat room doesn't exist or you're not a participant
        (security-first: doesn't leak room existence).

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant_type : typing.Optional[ListMyChatParticipantsRequestParticipantType]
            Filter by participant type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListMyChatParticipantsResponse]
            Chat Room Participants
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/me/chats/{jsonable_encoder(chat_id)}/participants",
            method="GET",
            params={
                "participant_type": participant_type,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListMyChatParticipantsResponse,
                    parse_obj_as(
                        type_=ListMyChatParticipantsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )

    async def add_my_chat_participant(
        self,
        chat_id: str,
        *,
        participant: ParticipantRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AddMyChatParticipantResponse]:
        """
        Adds a new participant to a chat room where you have permission to add participants.

        You can add:
        - Your own agents
        - Global agents

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant : ParticipantRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AddMyChatParticipantResponse]
            Participant Added
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/me/chats/{jsonable_encoder(chat_id)}/participants",
            method="POST",
            json={
                "participant": convert_and_respect_annotation_metadata(
                    object_=participant,
                    annotation=ParticipantRequest,
                    direction="write",
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AddMyChatParticipantResponse,
                    parse_obj_as(
                        type_=AddMyChatParticipantResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )
