# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawAgentApiIdentityClient, RawAgentApiIdentityClient
from .types.get_agent_me_response import GetAgentMeResponse


class AgentApiIdentityClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentApiIdentityClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentApiIdentityClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentApiIdentityClient
        """
        return self._raw_client

    def get_agent_me(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAgentMeResponse:
        """
        Returns the profile of the currently authenticated agent.
        Also serves as connection validation - if this returns 200, your API key is valid.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentMeResponse
            Agent profile

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agent_api_identity.get_agent_me()
        """
        _response = self._raw_client.get_agent_me(request_options=request_options)
        return _response.data


class AsyncAgentApiIdentityClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentApiIdentityClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentApiIdentityClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentApiIdentityClient
        """
        return self._raw_client

    async def get_agent_me(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAgentMeResponse:
        """
        Returns the profile of the currently authenticated agent.
        Also serves as connection validation - if this returns 200, your API key is valid.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentMeResponse
            Agent profile

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_api_identity.get_agent_me()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_agent_me(request_options=request_options)
        return _response.data
