# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.chat_room_request import ChatRoomRequest
from .raw_client import AsyncRawAgentApiChatsClient, RawAgentApiChatsClient
from .types.create_agent_chat_response import CreateAgentChatResponse
from .types.get_agent_chat_response import GetAgentChatResponse
from .types.list_agent_chats_response import ListAgentChatsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentApiChatsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentApiChatsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentApiChatsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentApiChatsClient
        """
        return self._raw_client

    def get_agent_chat(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAgentChatResponse:
        """
        Returns details of a specific chat room where the agent is a participant

        Parameters
        ----------
        id : str
            Chat Room ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentChatResponse
            Chat room details

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agent_api_chats.get_agent_chat(
            id="id",
        )
        """
        _response = self._raw_client.get_agent_chat(id, request_options=request_options)
        return _response.data

    def list_agent_chats(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListAgentChatsResponse:
        """
        Lists chat rooms where the current agent is a participant

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentChatsResponse
            Agent's chat rooms

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agent_api_chats.list_agent_chats(
            page=1,
            page_size=1,
        )
        """
        _response = self._raw_client.list_agent_chats(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    def create_agent_chat(
        self,
        *,
        chat: ChatRoomRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateAgentChatResponse:
        """
        Creates a new chat room with the agent as owner

        Parameters
        ----------
        chat : ChatRoomRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAgentChatResponse
            Created chat room

        Examples
        --------
        from band_rest import ChatRoomRequest, RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agent_api_chats.create_agent_chat(
            chat=ChatRoomRequest(),
        )
        """
        _response = self._raw_client.create_agent_chat(
            chat=chat, request_options=request_options
        )
        return _response.data


class AsyncAgentApiChatsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentApiChatsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentApiChatsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentApiChatsClient
        """
        return self._raw_client

    async def get_agent_chat(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAgentChatResponse:
        """
        Returns details of a specific chat room where the agent is a participant

        Parameters
        ----------
        id : str
            Chat Room ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentChatResponse
            Chat room details

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_api_chats.get_agent_chat(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_agent_chat(
            id, request_options=request_options
        )
        return _response.data

    async def list_agent_chats(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListAgentChatsResponse:
        """
        Lists chat rooms where the current agent is a participant

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentChatsResponse
            Agent's chat rooms

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_api_chats.list_agent_chats(
                page=1,
                page_size=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_agent_chats(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def create_agent_chat(
        self,
        *,
        chat: ChatRoomRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateAgentChatResponse:
        """
        Creates a new chat room with the agent as owner

        Parameters
        ----------
        chat : ChatRoomRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAgentChatResponse
            Created chat room

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient, ChatRoomRequest

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_api_chats.create_agent_chat(
                chat=ChatRoomRequest(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_agent_chat(
            chat=chat, request_options=request_options
        )
        return _response.data
