# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .agent_contact import AgentContact
    from .agent_contact_type import AgentContactType
    from .agent_me import AgentMe
    from .agent_memory_create_request_metadata import AgentMemoryCreateRequestMetadata
    from .agent_memory_create_request_scope import AgentMemoryCreateRequestScope
    from .agent_memory_create_request_segment import AgentMemoryCreateRequestSegment
    from .agent_memory_create_request_system import AgentMemoryCreateRequestSystem
    from .agent_memory_create_request_type import AgentMemoryCreateRequestType
    from .agent_memory_scope import AgentMemoryScope
    from .agent_memory_segment import AgentMemorySegment
    from .agent_memory_status import AgentMemoryStatus
    from .agent_memory_system import AgentMemorySystem
    from .agent_memory_type import AgentMemoryType
    from .agent_register_request import AgentRegisterRequest
    from .chat_event_message_type import ChatEventMessageType
    from .chat_event_request import ChatEventRequest
    from .chat_message import ChatMessage
    from .chat_message_request import ChatMessageRequest
    from .chat_message_request_mentions_item import ChatMessageRequestMentionsItem
    from .chat_participant import ChatParticipant
    from .chat_participant_details import ChatParticipantDetails
    from .chat_participant_details_type import ChatParticipantDetailsType
    from .chat_participant_type import ChatParticipantType
    from .chat_room import ChatRoom
    from .chat_room_request import ChatRoomRequest
    from .contact import Contact
    from .contact_contact_type import ContactContactType
    from .contact_request import ContactRequest
    from .contact_request_action_response import ContactRequestActionResponse
    from .contact_request_action_response_status import (
        ContactRequestActionResponseStatus,
    )
    from .contact_request_recipient import ContactRequestRecipient
    from .contact_request_recipient_type import ContactRequestRecipientType
    from .contact_request_requester import ContactRequestRequester
    from .contact_request_requester_type import ContactRequestRequesterType
    from .contact_request_status import ContactRequestStatus
    from .contact_user import ContactUser
    from .error import Error
    from .error_error import ErrorError
    from .event_created_response import EventCreatedResponse
    from .health_check import HealthCheck
    from .health_check_services import HealthCheckServices
    from .health_check_services_database import HealthCheckServicesDatabase
    from .health_check_services_oban import HealthCheckServicesOban
    from .memory import Memory
    from .memory_create_request import MemoryCreateRequest
    from .memory_create_request_metadata import MemoryCreateRequestMetadata
    from .memory_create_request_scope import MemoryCreateRequestScope
    from .memory_create_request_segment import MemoryCreateRequestSegment
    from .memory_create_request_system import MemoryCreateRequestSystem
    from .memory_create_request_type import MemoryCreateRequestType
    from .memory_scope import MemoryScope
    from .memory_segment import MemorySegment
    from .memory_status import MemoryStatus
    from .memory_system import MemorySystem
    from .memory_type import MemoryType
    from .message_sent_response import MessageSentResponse
    from .message_sent_response_recipients_item import MessageSentResponseRecipientsItem
    from .message_status_response import MessageStatusResponse
    from .message_status_response_status import MessageStatusResponseStatus
    from .my_agent import MyAgent
    from .participant_request import ParticipantRequest
    from .participant_request_role import ParticipantRequestRole
    from .participant_role import ParticipantRole
    from .peer import Peer
    from .peer_source import PeerSource
    from .peer_type import PeerType
    from .received_contact_request import ReceivedContactRequest
    from .received_contact_request_status import ReceivedContactRequestStatus
    from .resolved_entity import ResolvedEntity
    from .resolved_entity_type import ResolvedEntityType
    from .sent_contact_request import SentContactRequest
    from .sent_contact_request_status import SentContactRequestStatus
    from .test_response import TestResponse
    from .test_response_request_info import TestResponseRequestInfo
    from .user_details import UserDetails
    from .user_details_role import UserDetailsRole
    from .user_memory import UserMemory
    from .user_memory_scope import UserMemoryScope
    from .user_memory_segment import UserMemorySegment
    from .user_memory_status import UserMemoryStatus
    from .user_memory_system import UserMemorySystem
    from .user_memory_type import UserMemoryType
    from .validation_error import ValidationError
    from .validation_error_error import ValidationErrorError
_dynamic_imports: typing.Dict[str, str] = {
    "AgentContact": ".agent_contact",
    "AgentContactType": ".agent_contact_type",
    "AgentMe": ".agent_me",
    "AgentMemoryCreateRequestMetadata": ".agent_memory_create_request_metadata",
    "AgentMemoryCreateRequestScope": ".agent_memory_create_request_scope",
    "AgentMemoryCreateRequestSegment": ".agent_memory_create_request_segment",
    "AgentMemoryCreateRequestSystem": ".agent_memory_create_request_system",
    "AgentMemoryCreateRequestType": ".agent_memory_create_request_type",
    "AgentMemoryScope": ".agent_memory_scope",
    "AgentMemorySegment": ".agent_memory_segment",
    "AgentMemoryStatus": ".agent_memory_status",
    "AgentMemorySystem": ".agent_memory_system",
    "AgentMemoryType": ".agent_memory_type",
    "AgentRegisterRequest": ".agent_register_request",
    "ChatEventMessageType": ".chat_event_message_type",
    "ChatEventRequest": ".chat_event_request",
    "ChatMessage": ".chat_message",
    "ChatMessageRequest": ".chat_message_request",
    "ChatMessageRequestMentionsItem": ".chat_message_request_mentions_item",
    "ChatParticipant": ".chat_participant",
    "ChatParticipantDetails": ".chat_participant_details",
    "ChatParticipantDetailsType": ".chat_participant_details_type",
    "ChatParticipantType": ".chat_participant_type",
    "ChatRoom": ".chat_room",
    "ChatRoomRequest": ".chat_room_request",
    "Contact": ".contact",
    "ContactContactType": ".contact_contact_type",
    "ContactRequest": ".contact_request",
    "ContactRequestActionResponse": ".contact_request_action_response",
    "ContactRequestActionResponseStatus": ".contact_request_action_response_status",
    "ContactRequestRecipient": ".contact_request_recipient",
    "ContactRequestRecipientType": ".contact_request_recipient_type",
    "ContactRequestRequester": ".contact_request_requester",
    "ContactRequestRequesterType": ".contact_request_requester_type",
    "ContactRequestStatus": ".contact_request_status",
    "ContactUser": ".contact_user",
    "Error": ".error",
    "ErrorError": ".error_error",
    "EventCreatedResponse": ".event_created_response",
    "HealthCheck": ".health_check",
    "HealthCheckServices": ".health_check_services",
    "HealthCheckServicesDatabase": ".health_check_services_database",
    "HealthCheckServicesOban": ".health_check_services_oban",
    "Memory": ".memory",
    "MemoryCreateRequest": ".memory_create_request",
    "MemoryCreateRequestMetadata": ".memory_create_request_metadata",
    "MemoryCreateRequestScope": ".memory_create_request_scope",
    "MemoryCreateRequestSegment": ".memory_create_request_segment",
    "MemoryCreateRequestSystem": ".memory_create_request_system",
    "MemoryCreateRequestType": ".memory_create_request_type",
    "MemoryScope": ".memory_scope",
    "MemorySegment": ".memory_segment",
    "MemoryStatus": ".memory_status",
    "MemorySystem": ".memory_system",
    "MemoryType": ".memory_type",
    "MessageSentResponse": ".message_sent_response",
    "MessageSentResponseRecipientsItem": ".message_sent_response_recipients_item",
    "MessageStatusResponse": ".message_status_response",
    "MessageStatusResponseStatus": ".message_status_response_status",
    "MyAgent": ".my_agent",
    "ParticipantRequest": ".participant_request",
    "ParticipantRequestRole": ".participant_request_role",
    "ParticipantRole": ".participant_role",
    "Peer": ".peer",
    "PeerSource": ".peer_source",
    "PeerType": ".peer_type",
    "ReceivedContactRequest": ".received_contact_request",
    "ReceivedContactRequestStatus": ".received_contact_request_status",
    "ResolvedEntity": ".resolved_entity",
    "ResolvedEntityType": ".resolved_entity_type",
    "SentContactRequest": ".sent_contact_request",
    "SentContactRequestStatus": ".sent_contact_request_status",
    "TestResponse": ".test_response",
    "TestResponseRequestInfo": ".test_response_request_info",
    "UserDetails": ".user_details",
    "UserDetailsRole": ".user_details_role",
    "UserMemory": ".user_memory",
    "UserMemoryScope": ".user_memory_scope",
    "UserMemorySegment": ".user_memory_segment",
    "UserMemoryStatus": ".user_memory_status",
    "UserMemorySystem": ".user_memory_system",
    "UserMemoryType": ".user_memory_type",
    "ValidationError": ".validation_error",
    "ValidationErrorError": ".validation_error_error",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__}"
        )
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AgentContact",
    "AgentContactType",
    "AgentMe",
    "AgentMemoryCreateRequestMetadata",
    "AgentMemoryCreateRequestScope",
    "AgentMemoryCreateRequestSegment",
    "AgentMemoryCreateRequestSystem",
    "AgentMemoryCreateRequestType",
    "AgentMemoryScope",
    "AgentMemorySegment",
    "AgentMemoryStatus",
    "AgentMemorySystem",
    "AgentMemoryType",
    "AgentRegisterRequest",
    "ChatEventMessageType",
    "ChatEventRequest",
    "ChatMessage",
    "ChatMessageRequest",
    "ChatMessageRequestMentionsItem",
    "ChatParticipant",
    "ChatParticipantDetails",
    "ChatParticipantDetailsType",
    "ChatParticipantType",
    "ChatRoom",
    "ChatRoomRequest",
    "Contact",
    "ContactContactType",
    "ContactRequest",
    "ContactRequestActionResponse",
    "ContactRequestActionResponseStatus",
    "ContactRequestRecipient",
    "ContactRequestRecipientType",
    "ContactRequestRequester",
    "ContactRequestRequesterType",
    "ContactRequestStatus",
    "ContactUser",
    "Error",
    "ErrorError",
    "EventCreatedResponse",
    "HealthCheck",
    "HealthCheckServices",
    "HealthCheckServicesDatabase",
    "HealthCheckServicesOban",
    "Memory",
    "MemoryCreateRequest",
    "MemoryCreateRequestMetadata",
    "MemoryCreateRequestScope",
    "MemoryCreateRequestSegment",
    "MemoryCreateRequestSystem",
    "MemoryCreateRequestType",
    "MemoryScope",
    "MemorySegment",
    "MemoryStatus",
    "MemorySystem",
    "MemoryType",
    "MessageSentResponse",
    "MessageSentResponseRecipientsItem",
    "MessageStatusResponse",
    "MessageStatusResponseStatus",
    "MyAgent",
    "ParticipantRequest",
    "ParticipantRequestRole",
    "ParticipantRole",
    "Peer",
    "PeerSource",
    "PeerType",
    "ReceivedContactRequest",
    "ReceivedContactRequestStatus",
    "ResolvedEntity",
    "ResolvedEntityType",
    "SentContactRequest",
    "SentContactRequestStatus",
    "TestResponse",
    "TestResponseRequestInfo",
    "UserDetails",
    "UserDetailsRole",
    "UserMemory",
    "UserMemoryScope",
    "UserMemorySegment",
    "UserMemoryStatus",
    "UserMemorySystem",
    "UserMemoryType",
    "ValidationError",
    "ValidationErrorError",
]
