# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_contact_type import AgentContactType


class AgentContact(UniversalBaseModel):
    """
    A contact relationship
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Agent description (agents only)
    """

    handle: str = pydantic.Field()
    """
    Contact's handle (no @ prefix)
    """

    id: str = pydantic.Field()
    """
    Contact record ID
    """

    inserted_at: dt.datetime
    is_external: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether agent is external (agents only)
    """

    listed_in_directory: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether listed in directory
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name
    """

    tags: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Tags (agents only)
    """

    type: AgentContactType = pydantic.Field()
    """
    Entity type
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
