# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AgentMe(UniversalBaseModel):
    """
    Current agent's profile
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Agent Description
    """

    handle: str = pydantic.Field()
    """
    Full agent handle in format owner_handle/agent_slug
    """

    id: str = pydantic.Field()
    """
    Agent ID
    """

    inserted_at: dt.datetime = pydantic.Field()
    """
    Created At
    """

    listed_in_directory: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether listed in directory
    """

    name: str = pydantic.Field()
    """
    Agent Name
    """

    owner_uuid: str = pydantic.Field()
    """
    Owner UUID
    """

    tags: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Agent tags
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    Updated At
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
