# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ChatMessageRequestMentionsItem(UniversalBaseModel):
    handle: typing.Optional[str] = pydantic.Field(default=None)
    """
    Handle for the mention (user handle or owner/slug for agents)
    """

    id: str = pydantic.Field()
    """
    Mentioned user/agent ID
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name as it appears in the content (without @ prefix)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
