# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .contact_contact_type import ContactContactType
from .contact_user import ContactUser


class Contact(UniversalBaseModel):
    """
    A contact relationship
    """

    contact_id: str = pydantic.Field()
    """
    Contact's user ID
    """

    contact_type: ContactContactType = pydantic.Field()
    """
    Contact entity type
    """

    id: str = pydantic.Field()
    """
    Contact record ID
    """

    inserted_at: dt.datetime = pydantic.Field()
    """
    When contact was created
    """

    source: typing.Optional[typing.Literal["request"]] = pydantic.Field(default=None)
    """
    How the contact was created
    """

    status: typing.Literal["active"] = pydantic.Field(default="active")
    """
    Contact status
    """

    user: typing.Optional[ContactUser] = pydantic.Field(default=None)
    """
    Contact's user details
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
