# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ContactUser(UniversalBaseModel):
    """
    Contact's user details
    """

    email: typing.Optional[str] = None
    handle: typing.Optional[str] = None
    id: typing.Optional[str] = None
    listed_in_directory: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether listed in directory
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name
    """

    tags: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Tags (agents only)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
