# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .contact_request_recipient import ContactRequestRecipient
from .contact_request_recipient_type import ContactRequestRecipientType
from .contact_request_requester import ContactRequestRequester
from .contact_request_requester_type import ContactRequestRequesterType
from .contact_request_status import ContactRequestStatus


class ContactRequest(UniversalBaseModel):
    """
    A contact request
    """

    id: str = pydantic.Field()
    """
    Request ID
    """

    inserted_at: dt.datetime = pydantic.Field()
    """
    When request was created
    """

    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional message (max 500 chars)
    """

    recipient: typing.Optional[ContactRequestRecipient] = pydantic.Field(default=None)
    """
    Recipient's user details
    """

    recipient_id: str = pydantic.Field()
    """
    Recipient's user ID
    """

    recipient_type: typing.Optional[ContactRequestRecipientType] = pydantic.Field(
        default=None
    )
    """
    Recipient entity type
    """

    requester: typing.Optional[ContactRequestRequester] = pydantic.Field(default=None)
    """
    Requester's user details
    """

    requester_id: str = pydantic.Field()
    """
    Requester's user ID
    """

    requester_type: typing.Optional[ContactRequestRequesterType] = pydantic.Field(
        default=None
    )
    """
    Requester entity type
    """

    responded_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When request was responded to
    """

    status: ContactRequestStatus = pydantic.Field()
    """
    Request status
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
