# This file was auto-generated by Fern from our API Definition.

import typing

ContactRequestStatus = typing.Union[
    typing.Literal["pending", "approved", "rejected", "expired", "cancelled"],
    typing.Any,
]
