# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EventCreatedResponse(UniversalBaseModel):
    """
    Response after creating an event.
    """

    id: str = pydantic.Field()
    """
    ID of the created event
    """

    message_type: str = pydantic.Field()
    """
    Type of event recorded
    """

    success: bool = pydantic.Field()
    """
    Whether the event was created successfully
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
