# This file was auto-generated by Fern from our API Definition.

import typing

MemoryCreateRequestType = typing.Union[
    typing.Literal["iconic", "echoic", "haptic", "episodic", "semantic", "procedural"],
    typing.Any,
]
