# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .memory_create_request_metadata import MemoryCreateRequestMetadata
from .memory_create_request_scope import MemoryCreateRequestScope
from .memory_create_request_segment import MemoryCreateRequestSegment
from .memory_create_request_system import MemoryCreateRequestSystem
from .memory_create_request_type import MemoryCreateRequestType


class MemoryCreateRequest(UniversalBaseModel):
    """
    Request to create a new memory
    """

    content: str = pydantic.Field()
    """
    The memory content
    """

    metadata: typing.Optional[MemoryCreateRequestMetadata] = pydantic.Field(
        default=None
    )
    """
    Additional metadata (tags, references, etc.)
    """

    scope: typing.Optional[MemoryCreateRequestScope] = pydantic.Field(default=None)
    """
    Visibility: subject (cross-agent, about this subject) or organization (all agents)
    """

    segment: MemoryCreateRequestSegment = pydantic.Field()
    """
    Logical segment
    """

    subject_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    UUID of the subject this memory is about. Required for subject scope.
    """

    system: MemoryCreateRequestSystem = pydantic.Field()
    """
    Memory system tier
    """

    thought: str = pydantic.Field()
    """
    Agent's reasoning for storing this memory
    """

    type: MemoryCreateRequestType = pydantic.Field()
    """
    Memory type (must be valid for selected system)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
