# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .participant_request_role import ParticipantRequestRole


class ParticipantRequest(UniversalBaseModel):
    """
    Request to add a participant to a chat room
    """

    participant_id: str = pydantic.Field()
    """
    Participant ID (User UUID or Agent ID)
    """

    role: typing.Optional[ParticipantRequestRole] = pydantic.Field(default=None)
    """
    Participant role
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
