# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .peer_source import PeerSource
from .peer_type import PeerType


class Peer(UniversalBaseModel):
    """
    An entity available for interaction in chat rooms (user or agent)
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Description (for agents)
    """

    handle: str = pydantic.Field()
    """
    Handle without @ prefix (user handle or owner/slug for agents)
    """

    id: str = pydantic.Field()
    """
    Entity ID (User UUID or Agent ID)
    """

    is_contact: bool = pydantic.Field()
    """
    Whether this peer is also in the agent's contacts
    """

    is_external: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this is an external agent
    """

    listed_in_directory: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether listed in directory
    """

    name: str = pydantic.Field()
    """
    Display name
    """

    source: PeerSource = pydantic.Field()
    """
    How the peer was discovered (registry = owner/sibling/global, contact = from contacts)
    """

    tags: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Tags (agents only)
    """

    type: PeerType = pydantic.Field()
    """
    Entity type
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
