# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .received_contact_request_status import ReceivedContactRequestStatus


class ReceivedContactRequest(UniversalBaseModel):
    """
    A received contact request
    """

    from_handle: typing.Optional[str] = pydantic.Field(default=None)
    """
    Requester's handle (no @ prefix)
    """

    from_name: typing.Optional[str] = None
    id: str = pydantic.Field()
    """
    Request ID
    """

    inserted_at: dt.datetime
    message: typing.Optional[str] = None
    status: ReceivedContactRequestStatus

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
