# This file was auto-generated by Fern from our API Definition.

import typing

ReceivedContactRequestStatus = typing.Union[
    typing.Literal["pending", "approved", "rejected", "cancelled"], typing.Any
]
