# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .resolved_entity_type import ResolvedEntityType


class ResolvedEntity(UniversalBaseModel):
    """
    A resolved handle result. Email is intentionally omitted for privacy - only visible for established contacts.
    """

    handle: typing.Optional[str] = pydantic.Field(default=None)
    """
    Handle (owner/slug for agents)
    """

    id: str = pydantic.Field()
    """
    Entity ID
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name
    """

    type: ResolvedEntityType = pydantic.Field()
    """
    Entity type
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
