# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .sent_contact_request_status import SentContactRequestStatus


class SentContactRequest(UniversalBaseModel):
    """
    A sent contact request
    """

    id: str = pydantic.Field()
    """
    Request ID
    """

    inserted_at: dt.datetime
    message: typing.Optional[str] = None
    status: SentContactRequestStatus
    to_handle: typing.Optional[str] = pydantic.Field(default=None)
    """
    Recipient's handle (no @ prefix)
    """

    to_name: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
