# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawHumanApiMemoriesClient, RawHumanApiMemoriesClient
from .types.archive_user_memory_response import ArchiveUserMemoryResponse
from .types.get_user_memory_response import GetUserMemoryResponse
from .types.list_user_memories_response import ListUserMemoriesResponse
from .types.restore_user_memory_response import RestoreUserMemoryResponse
from .types.supersede_user_memory_response import SupersedeUserMemoryResponse


class HumanApiMemoriesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawHumanApiMemoriesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawHumanApiMemoriesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawHumanApiMemoriesClient
        """
        return self._raw_client

    def get_user_memory(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetUserMemoryResponse:
        """
        Retrieves a specific memory by ID if accessible to the user.

        Parameters
        ----------
        id : str
            Memory ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetUserMemoryResponse
            Memory

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_memories.get_user_memory(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
        )
        """
        _response = self._raw_client.get_user_memory(
            id, request_options=request_options
        )
        return _response.data

    def delete_user_memory(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Permanently deletes a memory. This is a hard delete - the memory cannot be recovered.

        Users can only delete memories that are about them (subject_id = user).

        Parameters
        ----------
        id : str
            Memory ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_memories.delete_user_memory(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
        )
        """
        _response = self._raw_client.delete_user_memory(
            id, request_options=request_options
        )
        return _response.data

    def supersede_user_memory(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SupersedeUserMemoryResponse:
        """
        Marks a memory as superseded (soft delete). Use when info is outdated/incorrect.
        The memory remains for audit trail but won't appear in normal queries.

        Users can only supersede memories that are about them (subject_id = user).

        Parameters
        ----------
        id : str
            Memory ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SupersedeUserMemoryResponse
            Superseded Memory

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_memories.supersede_user_memory(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
        )
        """
        _response = self._raw_client.supersede_user_memory(
            id, request_options=request_options
        )
        return _response.data

    def archive_user_memory(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ArchiveUserMemoryResponse:
        """
        Archives a memory (hides but preserves). Archived memories can be restored later.

        Users can only archive memories that are about them (subject_id = user).

        Parameters
        ----------
        id : str
            Memory ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ArchiveUserMemoryResponse
            Archived Memory

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_memories.archive_user_memory(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
        )
        """
        _response = self._raw_client.archive_user_memory(
            id, request_options=request_options
        )
        return _response.data

    def restore_user_memory(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RestoreUserMemoryResponse:
        """
        Restores an archived memory back to active status.
        Only works on memories with status 'archived'.

        Users can only restore memories that are about them (subject_id = user).

        Parameters
        ----------
        id : str
            Memory ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RestoreUserMemoryResponse
            Restored Memory

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_memories.restore_user_memory(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
        )
        """
        _response = self._raw_client.restore_user_memory(
            id, request_options=request_options
        )
        return _response.data

    def list_user_memories(
        self,
        *,
        chat_room_id: typing.Optional[str] = None,
        scope: typing.Optional[str] = None,
        system: typing.Optional[str] = None,
        type: typing.Optional[str] = None,
        segment: typing.Optional[str] = None,
        content_query: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        status: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListUserMemoriesResponse:
        """
        Lists memories accessible to the authenticated user:
        - Memories about the user (subject_id = user's UUID)
        - Organization-scoped memories in the user's organization
        - Optionally filter by chat room to see room-level memories

        Unlike agents, users can see memories from ALL agents in their organization
        that are about them or in rooms they participate in.

        Parameters
        ----------
        chat_room_id : typing.Optional[str]
            Filter by chat room ID

        scope : typing.Optional[str]
            Filter scope: about_me, organization, room, all

        system : typing.Optional[str]
            Filter by memory system

        type : typing.Optional[str]
            Filter by memory type

        segment : typing.Optional[str]
            Filter by segment

        content_query : typing.Optional[str]
            Full-text search query

        page_size : typing.Optional[int]
            Number of results per page (max 50)

        status : typing.Optional[str]
            Filter by status: active, superseded, archived, or all

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListUserMemoriesResponse
            User Memories

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_memories.list_user_memories(
            chat_room_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            scope="about_me",
            system="long_term",
            type="semantic",
            segment="user",
            content_query="prefers SUV",
            page_size=1,
            status="active",
        )
        """
        _response = self._raw_client.list_user_memories(
            chat_room_id=chat_room_id,
            scope=scope,
            system=system,
            type=type,
            segment=segment,
            content_query=content_query,
            page_size=page_size,
            status=status,
            request_options=request_options,
        )
        return _response.data


class AsyncHumanApiMemoriesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawHumanApiMemoriesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawHumanApiMemoriesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawHumanApiMemoriesClient
        """
        return self._raw_client

    async def get_user_memory(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetUserMemoryResponse:
        """
        Retrieves a specific memory by ID if accessible to the user.

        Parameters
        ----------
        id : str
            Memory ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetUserMemoryResponse
            Memory

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_memories.get_user_memory(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_user_memory(
            id, request_options=request_options
        )
        return _response.data

    async def delete_user_memory(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Permanently deletes a memory. This is a hard delete - the memory cannot be recovered.

        Users can only delete memories that are about them (subject_id = user).

        Parameters
        ----------
        id : str
            Memory ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_memories.delete_user_memory(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_user_memory(
            id, request_options=request_options
        )
        return _response.data

    async def supersede_user_memory(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SupersedeUserMemoryResponse:
        """
        Marks a memory as superseded (soft delete). Use when info is outdated/incorrect.
        The memory remains for audit trail but won't appear in normal queries.

        Users can only supersede memories that are about them (subject_id = user).

        Parameters
        ----------
        id : str
            Memory ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SupersedeUserMemoryResponse
            Superseded Memory

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_memories.supersede_user_memory(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.supersede_user_memory(
            id, request_options=request_options
        )
        return _response.data

    async def archive_user_memory(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ArchiveUserMemoryResponse:
        """
        Archives a memory (hides but preserves). Archived memories can be restored later.

        Users can only archive memories that are about them (subject_id = user).

        Parameters
        ----------
        id : str
            Memory ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ArchiveUserMemoryResponse
            Archived Memory

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_memories.archive_user_memory(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.archive_user_memory(
            id, request_options=request_options
        )
        return _response.data

    async def restore_user_memory(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RestoreUserMemoryResponse:
        """
        Restores an archived memory back to active status.
        Only works on memories with status 'archived'.

        Users can only restore memories that are about them (subject_id = user).

        Parameters
        ----------
        id : str
            Memory ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RestoreUserMemoryResponse
            Restored Memory

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_memories.restore_user_memory(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.restore_user_memory(
            id, request_options=request_options
        )
        return _response.data

    async def list_user_memories(
        self,
        *,
        chat_room_id: typing.Optional[str] = None,
        scope: typing.Optional[str] = None,
        system: typing.Optional[str] = None,
        type: typing.Optional[str] = None,
        segment: typing.Optional[str] = None,
        content_query: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        status: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListUserMemoriesResponse:
        """
        Lists memories accessible to the authenticated user:
        - Memories about the user (subject_id = user's UUID)
        - Organization-scoped memories in the user's organization
        - Optionally filter by chat room to see room-level memories

        Unlike agents, users can see memories from ALL agents in their organization
        that are about them or in rooms they participate in.

        Parameters
        ----------
        chat_room_id : typing.Optional[str]
            Filter by chat room ID

        scope : typing.Optional[str]
            Filter scope: about_me, organization, room, all

        system : typing.Optional[str]
            Filter by memory system

        type : typing.Optional[str]
            Filter by memory type

        segment : typing.Optional[str]
            Filter by segment

        content_query : typing.Optional[str]
            Full-text search query

        page_size : typing.Optional[int]
            Number of results per page (max 50)

        status : typing.Optional[str]
            Filter by status: active, superseded, archived, or all

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListUserMemoriesResponse
            User Memories

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_memories.list_user_memories(
                chat_room_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
                scope="about_me",
                system="long_term",
                type="semantic",
                segment="user",
                content_query="prefers SUV",
                page_size=1,
                status="active",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_user_memories(
            chat_room_id=chat_room_id,
            scope=scope,
            system=system,
            type=type,
            segment=segment,
            content_query=content_query,
            page_size=page_size,
            status=status,
            request_options=request_options,
        )
        return _response.data
