# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawAgentApiContextClient, RawAgentApiContextClient
from .types.get_agent_chat_context_response import GetAgentChatContextResponse


class AgentApiContextClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentApiContextClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentApiContextClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentApiContextClient
        """
        return self._raw_client

    def get_agent_chat_context(
        self,
        chat_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetAgentChatContextResponse:
        """
        Returns all messages relevant to the agent for execution context/rehydration.

        This includes:
        - All messages the agent sent (any type: text, tool_call, tool_result, thought, etc.)
        - All text messages that @mention the agent

        Use this endpoint to load the complete context an external agent needs to resume execution.

        Messages are returned in chronological order (oldest first).

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        page : typing.Optional[int]
            Page number (default: 1)

        page_size : typing.Optional[int]
            Items per page (default: 50, max: 100)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentChatContextResponse
            Agent context

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agent_api_context.get_agent_chat_context(
            chat_id="chat_id",
            page=1,
            page_size=1,
        )
        """
        _response = self._raw_client.get_agent_chat_context(
            chat_id, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data


class AsyncAgentApiContextClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentApiContextClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentApiContextClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentApiContextClient
        """
        return self._raw_client

    async def get_agent_chat_context(
        self,
        chat_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetAgentChatContextResponse:
        """
        Returns all messages relevant to the agent for execution context/rehydration.

        This includes:
        - All messages the agent sent (any type: text, tool_call, tool_result, thought, etc.)
        - All text messages that @mention the agent

        Use this endpoint to load the complete context an external agent needs to resume execution.

        Messages are returned in chronological order (oldest first).

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        page : typing.Optional[int]
            Page number (default: 1)

        page_size : typing.Optional[int]
            Items per page (default: 50, max: 100)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentChatContextResponse
            Agent context

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_api_context.get_agent_chat_context(
                chat_id="chat_id",
                page=1,
                page_size=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_agent_chat_context(
            chat_id, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data
