"""Shared Oh My P.I. ACP protocol constants.

This module has no ACP-package dependency, so examples and every test lane can
share OMP's command and environment contract.
"""

from __future__ import annotations

DEFAULT_OMP_MODEL = "openai/gpt-5.4-mini"
OMP_ACP_SUBCOMMAND = "acp"
OMP_ALWAYS_ASK_APPROVAL_MODE = "always-ask"
OMP_APPROVAL_MODE_ARGUMENT = "--approval-mode"
OMP_APPROVAL_MODE_ASSIGNMENT_PREFIX = f"{OMP_APPROVAL_MODE_ARGUMENT}="
OMP_AUTO_APPROVE_ARGUMENT = "--auto-approve"
OMP_WRITE_APPROVAL_MODE = "write"
OMP_YOLO_APPROVAL_MODE = "yolo"
OMP_AUTO_APPROVAL_MODES = frozenset({OMP_WRITE_APPROVAL_MODE, OMP_YOLO_APPROVAL_MODE})
OMP_BINARY = "omp"
OMP_COMMAND: tuple[str, ...] = (OMP_BINARY, OMP_ACP_SUBCOMMAND)
OMP_ELICITATION_APPROVE_OPTION = "Approve"
OMP_ELICITATION_CALL_ID_PREFIX = "omp-elicitation"
OMP_ELICITATION_DENY_OPTION = "Deny"
OMP_ELICITATION_FIELD = "value"
OMP_ELICITATION_MESSAGE_FIELD = "message"
OMP_ELICITATION_TOOL_NAME = "OMP approval"
OMP_GEMINI_API_KEY_ENV = "GEMINI_API_KEY"
OMP_MCP_CONTENT_FIELD = "content"
OMP_MCP_DEVICE_PREFIX = "xd://mcp__"
OMP_MCP_PATH_FIELD = "path"
OMP_MODEL_ARGUMENT = "--model"
OMP_OPENAI_API_KEY_ENV = "OPENAI_API_KEY"
OMP_STATE_DIRECTORY_ENV = "PI_CODING_AGENT_DIR"
OMP_YOLO_ARGUMENT = "--yolo"

__all__ = [
    "DEFAULT_OMP_MODEL",
    "OMP_ACP_SUBCOMMAND",
    "OMP_ALWAYS_ASK_APPROVAL_MODE",
    "OMP_APPROVAL_MODE_ARGUMENT",
    "OMP_APPROVAL_MODE_ASSIGNMENT_PREFIX",
    "OMP_AUTO_APPROVE_ARGUMENT",
    "OMP_AUTO_APPROVAL_MODES",
    "OMP_BINARY",
    "OMP_COMMAND",
    "OMP_ELICITATION_APPROVE_OPTION",
    "OMP_ELICITATION_CALL_ID_PREFIX",
    "OMP_ELICITATION_DENY_OPTION",
    "OMP_ELICITATION_FIELD",
    "OMP_ELICITATION_MESSAGE_FIELD",
    "OMP_ELICITATION_TOOL_NAME",
    "OMP_GEMINI_API_KEY_ENV",
    "OMP_MCP_CONTENT_FIELD",
    "OMP_MCP_DEVICE_PREFIX",
    "OMP_MCP_PATH_FIELD",
    "OMP_MODEL_ARGUMENT",
    "OMP_OPENAI_API_KEY_ENV",
    "OMP_STATE_DIRECTORY_ENV",
    "OMP_WRITE_APPROVAL_MODE",
    "OMP_YOLO_APPROVAL_MODE",
    "OMP_YOLO_ARGUMENT",
]
