# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawHumanApiChatsClient, RawHumanApiChatsClient
from .types.create_my_chat_room_request_chat import CreateMyChatRoomRequestChat
from .types.create_my_chat_room_response import CreateMyChatRoomResponse
from .types.get_my_chat_room_response import GetMyChatRoomResponse
from .types.list_my_chats_response import ListMyChatsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class HumanApiChatsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawHumanApiChatsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawHumanApiChatsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawHumanApiChatsClient
        """
        return self._raw_client

    def list_my_chats(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMyChatsResponse:
        """
        Returns a paginated list of all chat rooms where you are a participant.

        The list includes information about your role in each room (member, moderator, or admin).
        Shows only rooms you have access to based on your participation.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number for pagination

        page_size : typing.Optional[int]
            Number of items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMyChatsResponse
            Chat Rooms

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_chats.list_my_chats(
            page=1,
            page_size=1,
        )
        """
        _response = self._raw_client.list_my_chats(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    def create_my_chat_room(
        self,
        *,
        chat: CreateMyChatRoomRequestChat,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMyChatRoomResponse:
        """
        Creates a new chat room with you as the owner.

        The chat room title is auto-generated from the first message.
        You can optionally associate the chat room with a task by providing a task_id.

        Parameters
        ----------
        chat : CreateMyChatRoomRequestChat

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMyChatRoomResponse
            Created Chat Room

        Examples
        --------
        from band_rest import RestClient
        from band_rest.human_api_chats import CreateMyChatRoomRequestChat

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_chats.create_my_chat_room(
            chat=CreateMyChatRoomRequestChat(),
        )
        """
        _response = self._raw_client.create_my_chat_room(
            chat=chat, request_options=request_options
        )
        return _response.data

    def get_my_chat_room(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetMyChatRoomResponse:
        """
        Returns details of a specific chat room where you are a participant.

        Returns 404 if the room doesn't exist or if you're not a participant
        (security-first: doesn't leak room existence).

        Parameters
        ----------
        id : str
            Chat Room ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetMyChatRoomResponse
            Chat Room

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_chats.get_my_chat_room(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
        )
        """
        _response = self._raw_client.get_my_chat_room(
            id, request_options=request_options
        )
        return _response.data


class AsyncHumanApiChatsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawHumanApiChatsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawHumanApiChatsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawHumanApiChatsClient
        """
        return self._raw_client

    async def list_my_chats(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMyChatsResponse:
        """
        Returns a paginated list of all chat rooms where you are a participant.

        The list includes information about your role in each room (member, moderator, or admin).
        Shows only rooms you have access to based on your participation.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number for pagination

        page_size : typing.Optional[int]
            Number of items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMyChatsResponse
            Chat Rooms

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_chats.list_my_chats(
                page=1,
                page_size=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_my_chats(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def create_my_chat_room(
        self,
        *,
        chat: CreateMyChatRoomRequestChat,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMyChatRoomResponse:
        """
        Creates a new chat room with you as the owner.

        The chat room title is auto-generated from the first message.
        You can optionally associate the chat room with a task by providing a task_id.

        Parameters
        ----------
        chat : CreateMyChatRoomRequestChat

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMyChatRoomResponse
            Created Chat Room

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient
        from band_rest.human_api_chats import CreateMyChatRoomRequestChat

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_chats.create_my_chat_room(
                chat=CreateMyChatRoomRequestChat(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_my_chat_room(
            chat=chat, request_options=request_options
        )
        return _response.data

    async def get_my_chat_room(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetMyChatRoomResponse:
        """
        Returns details of a specific chat room where you are a participant.

        Returns 404 if the room doesn't exist or if you're not a participant
        (security-first: doesn't leak room existence).

        Parameters
        ----------
        id : str
            Chat Room ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetMyChatRoomResponse
            Chat Room

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_chats.get_my_chat_room(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_my_chat_room(
            id, request_options=request_options
        )
        return _response.data
