# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_agent_chat_message_response import CreateAgentChatMessageResponse
    from .get_agent_next_message_response import GetAgentNextMessageResponse
    from .list_agent_messages_request_status import ListAgentMessagesRequestStatus
    from .list_agent_messages_response import ListAgentMessagesResponse
    from .list_agent_messages_response_metadata import ListAgentMessagesResponseMetadata
    from .mark_agent_message_failed_response import MarkAgentMessageFailedResponse
    from .mark_agent_message_processed_response import MarkAgentMessageProcessedResponse
    from .mark_agent_message_processing_response import (
        MarkAgentMessageProcessingResponse,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "CreateAgentChatMessageResponse": ".create_agent_chat_message_response",
    "GetAgentNextMessageResponse": ".get_agent_next_message_response",
    "ListAgentMessagesRequestStatus": ".list_agent_messages_request_status",
    "ListAgentMessagesResponse": ".list_agent_messages_response",
    "ListAgentMessagesResponseMetadata": ".list_agent_messages_response_metadata",
    "MarkAgentMessageFailedResponse": ".mark_agent_message_failed_response",
    "MarkAgentMessageProcessedResponse": ".mark_agent_message_processed_response",
    "MarkAgentMessageProcessingResponse": ".mark_agent_message_processing_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__}"
        )
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateAgentChatMessageResponse",
    "GetAgentNextMessageResponse",
    "ListAgentMessagesRequestStatus",
    "ListAgentMessagesResponse",
    "ListAgentMessagesResponseMetadata",
    "MarkAgentMessageFailedResponse",
    "MarkAgentMessageProcessedResponse",
    "MarkAgentMessageProcessingResponse",
]
