# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawAgentApiContactsClient, RawAgentApiContactsClient
from .types.add_agent_contact_response import AddAgentContactResponse
from .types.list_agent_contact_requests_request_sent_status import (
    ListAgentContactRequestsRequestSentStatus,
)
from .types.list_agent_contact_requests_response import ListAgentContactRequestsResponse
from .types.list_agent_contacts_response import ListAgentContactsResponse
from .types.remove_agent_contact_response import RemoveAgentContactResponse
from .types.respond_to_agent_contact_request_request_action import (
    RespondToAgentContactRequestRequestAction,
)
from .types.respond_to_agent_contact_request_response import (
    RespondToAgentContactRequestResponse,
)

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentApiContactsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentApiContactsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentApiContactsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentApiContactsClient
        """
        return self._raw_client

    def respond_to_agent_contact_request(
        self,
        *,
        action: RespondToAgentContactRequestRequestAction,
        handle: typing.Optional[str] = OMIT,
        request_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RespondToAgentContactRequestResponse:
        """
        Approve, reject, or cancel a contact request.

        - `approve`/`reject`: For requests you RECEIVED (handle = requester's handle)
        - `cancel`: For requests you SENT (handle = recipient's handle)

        Parameters
        ----------
        action : RespondToAgentContactRequestRequestAction

        handle : typing.Optional[str]
            Other party's handle

        request_id : typing.Optional[str]
            Or request ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RespondToAgentContactRequestResponse
            Response recorded

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agent_api_contacts.respond_to_agent_contact_request(
            action="approve",
        )
        """
        _response = self._raw_client.respond_to_agent_contact_request(
            action=action,
            handle=handle,
            request_id=request_id,
            request_options=request_options,
        )
        return _response.data

    def add_agent_contact(
        self,
        *,
        handle: str,
        message: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddAgentContactResponse:
        """
        Resolves handle and sends contact request.

        Returns `pending` when a new request is created.
        Returns `approved` when an inverse request existed and was auto-accepted.

        Parameters
        ----------
        handle : str
            Handle to add

        message : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddAgentContactResponse
            Request sent or contact created

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agent_api_contacts.add_agent_contact(
            handle="@john",
        )
        """
        _response = self._raw_client.add_agent_contact(
            handle=handle, message=message, request_options=request_options
        )
        return _response.data

    def list_agent_contact_requests(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sent_status: typing.Optional[ListAgentContactRequestsRequestSentStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListAgentContactRequestsResponse:
        """
        Returns both received and sent requests with handles and pagination metadata.

        - Received requests are always filtered to pending status.
        - Sent requests can be filtered by status using `sent_status` parameter.
        - Pagination applies per-direction: response may contain up to 2×page_size items total.
        - Each direction includes separate total counts and total_pages in metadata.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page per direction (max 100)

        sent_status : typing.Optional[ListAgentContactRequestsRequestSentStatus]
            Filter sent requests by status (default: pending)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentContactRequestsResponse
            Requests list

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agent_api_contacts.list_agent_contact_requests(
            page=1,
            page_size=1,
            sent_status="pending",
        )
        """
        _response = self._raw_client.list_agent_contact_requests(
            page=page,
            page_size=page_size,
            sent_status=sent_status,
            request_options=request_options,
        )
        return _response.data

    def list_agent_contacts(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListAgentContactsResponse:
        """
        Returns contacts with handles for easy reference.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentContactsResponse
            Contacts list

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agent_api_contacts.list_agent_contacts(
            page=1,
            page_size=1,
        )
        """
        _response = self._raw_client.list_agent_contacts(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    def remove_agent_contact(
        self,
        *,
        contact_id: typing.Optional[str] = OMIT,
        handle: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RemoveAgentContactResponse:
        """
        Removes contact by handle or ID.

        Parameters
        ----------
        contact_id : typing.Optional[str]
            Or contact record ID

        handle : typing.Optional[str]
            Contact's handle

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RemoveAgentContactResponse
            Removed

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agent_api_contacts.remove_agent_contact()
        """
        _response = self._raw_client.remove_agent_contact(
            contact_id=contact_id, handle=handle, request_options=request_options
        )
        return _response.data


class AsyncAgentApiContactsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentApiContactsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentApiContactsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentApiContactsClient
        """
        return self._raw_client

    async def respond_to_agent_contact_request(
        self,
        *,
        action: RespondToAgentContactRequestRequestAction,
        handle: typing.Optional[str] = OMIT,
        request_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RespondToAgentContactRequestResponse:
        """
        Approve, reject, or cancel a contact request.

        - `approve`/`reject`: For requests you RECEIVED (handle = requester's handle)
        - `cancel`: For requests you SENT (handle = recipient's handle)

        Parameters
        ----------
        action : RespondToAgentContactRequestRequestAction

        handle : typing.Optional[str]
            Other party's handle

        request_id : typing.Optional[str]
            Or request ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RespondToAgentContactRequestResponse
            Response recorded

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_api_contacts.respond_to_agent_contact_request(
                action="approve",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.respond_to_agent_contact_request(
            action=action,
            handle=handle,
            request_id=request_id,
            request_options=request_options,
        )
        return _response.data

    async def add_agent_contact(
        self,
        *,
        handle: str,
        message: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddAgentContactResponse:
        """
        Resolves handle and sends contact request.

        Returns `pending` when a new request is created.
        Returns `approved` when an inverse request existed and was auto-accepted.

        Parameters
        ----------
        handle : str
            Handle to add

        message : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddAgentContactResponse
            Request sent or contact created

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_api_contacts.add_agent_contact(
                handle="@john",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_agent_contact(
            handle=handle, message=message, request_options=request_options
        )
        return _response.data

    async def list_agent_contact_requests(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sent_status: typing.Optional[ListAgentContactRequestsRequestSentStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListAgentContactRequestsResponse:
        """
        Returns both received and sent requests with handles and pagination metadata.

        - Received requests are always filtered to pending status.
        - Sent requests can be filtered by status using `sent_status` parameter.
        - Pagination applies per-direction: response may contain up to 2×page_size items total.
        - Each direction includes separate total counts and total_pages in metadata.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page per direction (max 100)

        sent_status : typing.Optional[ListAgentContactRequestsRequestSentStatus]
            Filter sent requests by status (default: pending)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentContactRequestsResponse
            Requests list

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_api_contacts.list_agent_contact_requests(
                page=1,
                page_size=1,
                sent_status="pending",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_agent_contact_requests(
            page=page,
            page_size=page_size,
            sent_status=sent_status,
            request_options=request_options,
        )
        return _response.data

    async def list_agent_contacts(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListAgentContactsResponse:
        """
        Returns contacts with handles for easy reference.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentContactsResponse
            Contacts list

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_api_contacts.list_agent_contacts(
                page=1,
                page_size=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_agent_contacts(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def remove_agent_contact(
        self,
        *,
        contact_id: typing.Optional[str] = OMIT,
        handle: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RemoveAgentContactResponse:
        """
        Removes contact by handle or ID.

        Parameters
        ----------
        contact_id : typing.Optional[str]
            Or contact record ID

        handle : typing.Optional[str]
            Contact's handle

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RemoveAgentContactResponse
            Removed

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_api_contacts.remove_agent_contact()


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_agent_contact(
            contact_id=contact_id, handle=handle, request_options=request_options
        )
        return _response.data
