# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .add_agent_contact_response import AddAgentContactResponse
    from .add_agent_contact_response_data import AddAgentContactResponseData
    from .add_agent_contact_response_data_status import (
        AddAgentContactResponseDataStatus,
    )
    from .list_agent_contact_requests_request_sent_status import (
        ListAgentContactRequestsRequestSentStatus,
    )
    from .list_agent_contact_requests_response import ListAgentContactRequestsResponse
    from .list_agent_contact_requests_response_data import (
        ListAgentContactRequestsResponseData,
    )
    from .list_agent_contact_requests_response_metadata import (
        ListAgentContactRequestsResponseMetadata,
    )
    from .list_agent_contact_requests_response_metadata_received import (
        ListAgentContactRequestsResponseMetadataReceived,
    )
    from .list_agent_contact_requests_response_metadata_sent import (
        ListAgentContactRequestsResponseMetadataSent,
    )
    from .list_agent_contacts_response import ListAgentContactsResponse
    from .list_agent_contacts_response_metadata import ListAgentContactsResponseMetadata
    from .remove_agent_contact_response import RemoveAgentContactResponse
    from .remove_agent_contact_response_data import RemoveAgentContactResponseData
    from .respond_to_agent_contact_request_request_action import (
        RespondToAgentContactRequestRequestAction,
    )
    from .respond_to_agent_contact_request_response import (
        RespondToAgentContactRequestResponse,
    )
    from .respond_to_agent_contact_request_response_data import (
        RespondToAgentContactRequestResponseData,
    )
    from .respond_to_agent_contact_request_response_data_status import (
        RespondToAgentContactRequestResponseDataStatus,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "AddAgentContactResponse": ".add_agent_contact_response",
    "AddAgentContactResponseData": ".add_agent_contact_response_data",
    "AddAgentContactResponseDataStatus": ".add_agent_contact_response_data_status",
    "ListAgentContactRequestsRequestSentStatus": ".list_agent_contact_requests_request_sent_status",
    "ListAgentContactRequestsResponse": ".list_agent_contact_requests_response",
    "ListAgentContactRequestsResponseData": ".list_agent_contact_requests_response_data",
    "ListAgentContactRequestsResponseMetadata": ".list_agent_contact_requests_response_metadata",
    "ListAgentContactRequestsResponseMetadataReceived": ".list_agent_contact_requests_response_metadata_received",
    "ListAgentContactRequestsResponseMetadataSent": ".list_agent_contact_requests_response_metadata_sent",
    "ListAgentContactsResponse": ".list_agent_contacts_response",
    "ListAgentContactsResponseMetadata": ".list_agent_contacts_response_metadata",
    "RemoveAgentContactResponse": ".remove_agent_contact_response",
    "RemoveAgentContactResponseData": ".remove_agent_contact_response_data",
    "RespondToAgentContactRequestRequestAction": ".respond_to_agent_contact_request_request_action",
    "RespondToAgentContactRequestResponse": ".respond_to_agent_contact_request_response",
    "RespondToAgentContactRequestResponseData": ".respond_to_agent_contact_request_response_data",
    "RespondToAgentContactRequestResponseDataStatus": ".respond_to_agent_contact_request_response_data_status",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__}"
        )
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AddAgentContactResponse",
    "AddAgentContactResponseData",
    "AddAgentContactResponseDataStatus",
    "ListAgentContactRequestsRequestSentStatus",
    "ListAgentContactRequestsResponse",
    "ListAgentContactRequestsResponseData",
    "ListAgentContactRequestsResponseMetadata",
    "ListAgentContactRequestsResponseMetadataReceived",
    "ListAgentContactRequestsResponseMetadataSent",
    "ListAgentContactsResponse",
    "ListAgentContactsResponseMetadata",
    "RemoveAgentContactResponse",
    "RemoveAgentContactResponseData",
    "RespondToAgentContactRequestRequestAction",
    "RespondToAgentContactRequestResponse",
    "RespondToAgentContactRequestResponseData",
    "RespondToAgentContactRequestResponseDataStatus",
]
