# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .list_agent_contact_requests_response_metadata_received import (
    ListAgentContactRequestsResponseMetadataReceived,
)
from .list_agent_contact_requests_response_metadata_sent import (
    ListAgentContactRequestsResponseMetadataSent,
)


class ListAgentContactRequestsResponseMetadata(UniversalBaseModel):
    """
    Pagination metadata. Note: page_size applies per-direction, so response may contain up to 2×page_size items.
    """

    page: int
    page_size: int
    received: ListAgentContactRequestsResponseMetadataReceived
    sent: ListAgentContactRequestsResponseMetadataSent

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
