# This file was auto-generated by Fern from our API Definition.

import typing

ListAgentContactRequestsRequestSentStatus = typing.Union[
    typing.Literal["pending", "approved", "rejected", "cancelled", "all"], typing.Any
]
