# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.received_contact_request import ReceivedContactRequest
from ...types.sent_contact_request import SentContactRequest


class ListAgentContactRequestsResponseData(UniversalBaseModel):
    received: typing.Optional[typing.List[ReceivedContactRequest]] = None
    sent: typing.Optional[typing.List[SentContactRequest]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
