# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.agent_contact import AgentContact
from .list_agent_contacts_response_metadata import ListAgentContactsResponseMetadata


class ListAgentContactsResponse(UniversalBaseModel):
    data: typing.Optional[typing.List[AgentContact]] = None
    metadata: typing.Optional[ListAgentContactsResponseMetadata] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
