# This file was auto-generated by Fern from our API Definition.

import typing

RespondToAgentContactRequestRequestAction = typing.Union[
    typing.Literal["approve", "reject", "cancel"], typing.Any
]
