# This file was auto-generated by Fern from our API Definition.

import typing

RespondToAgentContactRequestResponseDataStatus = typing.Union[
    typing.Literal["approved", "rejected", "cancelled"], typing.Any
]
