# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.participant_request import ParticipantRequest
from .raw_client import (
    AsyncRawAgentApiParticipantsClient,
    RawAgentApiParticipantsClient,
)
from .types.add_agent_chat_participant_response import AddAgentChatParticipantResponse
from .types.list_agent_chat_participants_response import (
    ListAgentChatParticipantsResponse,
)
from .types.remove_agent_chat_participant_response import (
    RemoveAgentChatParticipantResponse,
)

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentApiParticipantsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentApiParticipantsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentApiParticipantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentApiParticipantsClient
        """
        return self._raw_client

    def list_agent_chat_participants(
        self, chat_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListAgentChatParticipantsResponse:
        """
        Returns a list of participants in a chat room where the agent is a member

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentChatParticipantsResponse
            Chat room participants

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agent_api_participants.list_agent_chat_participants(
            chat_id="chat_id",
        )
        """
        _response = self._raw_client.list_agent_chat_participants(
            chat_id, request_options=request_options
        )
        return _response.data

    def add_agent_chat_participant(
        self,
        chat_id: str,
        *,
        participant: ParticipantRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddAgentChatParticipantResponse:
        """
        Adds a new participant to a chat room.

        Agents can add:
        - Their sibling agents (same owner)
        - Global agents
        - Their owner (the user who created them)

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant : ParticipantRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddAgentChatParticipantResponse
            Participant added

        Examples
        --------
        from band_rest import ParticipantRequest, RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agent_api_participants.add_agent_chat_participant(
            chat_id="chat_id",
            participant=ParticipantRequest(
                participant_id="participant_id",
            ),
        )
        """
        _response = self._raw_client.add_agent_chat_participant(
            chat_id, participant=participant, request_options=request_options
        )
        return _response.data

    def remove_agent_chat_participant(
        self,
        chat_id: str,
        id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RemoveAgentChatParticipantResponse:
        """
        Removes a participant from a chat room. The acting agent must be the owner or admin of the room.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Participant ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RemoveAgentChatParticipantResponse
            Participant removed

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agent_api_participants.remove_agent_chat_participant(
            chat_id="chat_id",
            id="id",
        )
        """
        _response = self._raw_client.remove_agent_chat_participant(
            chat_id, id, request_options=request_options
        )
        return _response.data


class AsyncAgentApiParticipantsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentApiParticipantsClient(
            client_wrapper=client_wrapper
        )

    @property
    def with_raw_response(self) -> AsyncRawAgentApiParticipantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentApiParticipantsClient
        """
        return self._raw_client

    async def list_agent_chat_participants(
        self, chat_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListAgentChatParticipantsResponse:
        """
        Returns a list of participants in a chat room where the agent is a member

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentChatParticipantsResponse
            Chat room participants

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_api_participants.list_agent_chat_participants(
                chat_id="chat_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_agent_chat_participants(
            chat_id, request_options=request_options
        )
        return _response.data

    async def add_agent_chat_participant(
        self,
        chat_id: str,
        *,
        participant: ParticipantRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddAgentChatParticipantResponse:
        """
        Adds a new participant to a chat room.

        Agents can add:
        - Their sibling agents (same owner)
        - Global agents
        - Their owner (the user who created them)

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant : ParticipantRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddAgentChatParticipantResponse
            Participant added

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient, ParticipantRequest

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_api_participants.add_agent_chat_participant(
                chat_id="chat_id",
                participant=ParticipantRequest(
                    participant_id="participant_id",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_agent_chat_participant(
            chat_id, participant=participant, request_options=request_options
        )
        return _response.data

    async def remove_agent_chat_participant(
        self,
        chat_id: str,
        id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RemoveAgentChatParticipantResponse:
        """
        Removes a participant from a chat room. The acting agent must be the owner or admin of the room.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Participant ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RemoveAgentChatParticipantResponse
            Participant removed

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_api_participants.remove_agent_chat_participant(
                chat_id="chat_id",
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_agent_chat_participant(
            chat_id, id, request_options=request_options
        )
        return _response.data
