# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .environment import RestClientEnvironment

if typing.TYPE_CHECKING:
    from .agent_api_chats.client import AgentApiChatsClient, AsyncAgentApiChatsClient
    from .agent_api_contacts.client import (
        AgentApiContactsClient,
        AsyncAgentApiContactsClient,
    )
    from .agent_api_context.client import (
        AgentApiContextClient,
        AsyncAgentApiContextClient,
    )
    from .agent_api_events.client import AgentApiEventsClient, AsyncAgentApiEventsClient
    from .agent_api_identity.client import (
        AgentApiIdentityClient,
        AsyncAgentApiIdentityClient,
    )
    from .agent_api_memories.client import (
        AgentApiMemoriesClient,
        AsyncAgentApiMemoriesClient,
    )
    from .agent_api_messages.client import (
        AgentApiMessagesClient,
        AsyncAgentApiMessagesClient,
    )
    from .agent_api_participants.client import (
        AgentApiParticipantsClient,
        AsyncAgentApiParticipantsClient,
    )
    from .agent_api_peers.client import AgentApiPeersClient, AsyncAgentApiPeersClient
    from .human_api_agents.client import AsyncHumanApiAgentsClient, HumanApiAgentsClient
    from .human_api_chats.client import AsyncHumanApiChatsClient, HumanApiChatsClient
    from .human_api_contacts.client import (
        AsyncHumanApiContactsClient,
        HumanApiContactsClient,
    )
    from .human_api_memories.client import (
        AsyncHumanApiMemoriesClient,
        HumanApiMemoriesClient,
    )
    from .human_api_messages.client import (
        AsyncHumanApiMessagesClient,
        HumanApiMessagesClient,
    )
    from .human_api_participants.client import (
        AsyncHumanApiParticipantsClient,
        HumanApiParticipantsClient,
    )
    from .human_api_peers.client import AsyncHumanApiPeersClient, HumanApiPeersClient
    from .human_api_profile.client import (
        AsyncHumanApiProfileClient,
        HumanApiProfileClient,
    )
    from .system.client import AsyncSystemClient, SystemClient
    from .test.client import AsyncTestClient, TestClient


class RestClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : RestClientEnvironment
        The environment to use for requests from the client. from .environment import RestClientEnvironment



        Defaults to RestClientEnvironment.DEFAULT



    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    from band_rest import RestClient

    client = RestClient(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: RestClientEnvironment = RestClientEnvironment.DEFAULT,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
    ):
        _defaulted_timeout = (
            timeout
            if timeout is not None
            else 60
            if httpx_client is None
            else httpx_client.timeout.read
        )
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(
                timeout=_defaulted_timeout, follow_redirects=follow_redirects
            )
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
        )
        self._agent_api_contacts: typing.Optional[AgentApiContactsClient] = None
        self._human_api_contacts: typing.Optional[HumanApiContactsClient] = None
        self._human_api_memories: typing.Optional[HumanApiMemoriesClient] = None
        self._human_api_chats: typing.Optional[HumanApiChatsClient] = None
        self._agent_api_messages: typing.Optional[AgentApiMessagesClient] = None
        self._agent_api_memories: typing.Optional[AgentApiMemoriesClient] = None
        self._system: typing.Optional[SystemClient] = None
        self._agent_api_peers: typing.Optional[AgentApiPeersClient] = None
        self._human_api_peers: typing.Optional[HumanApiPeersClient] = None
        self._human_api_messages: typing.Optional[HumanApiMessagesClient] = None
        self._agent_api_events: typing.Optional[AgentApiEventsClient] = None
        self._human_api_agents: typing.Optional[HumanApiAgentsClient] = None
        self._human_api_participants: typing.Optional[HumanApiParticipantsClient] = None
        self._agent_api_identity: typing.Optional[AgentApiIdentityClient] = None
        self._agent_api_participants: typing.Optional[AgentApiParticipantsClient] = None
        self._agent_api_context: typing.Optional[AgentApiContextClient] = None
        self._agent_api_chats: typing.Optional[AgentApiChatsClient] = None
        self._test: typing.Optional[TestClient] = None
        self._human_api_profile: typing.Optional[HumanApiProfileClient] = None

    @property
    def agent_api_contacts(self):
        if self._agent_api_contacts is None:
            from .agent_api_contacts.client import AgentApiContactsClient  # noqa: E402

            self._agent_api_contacts = AgentApiContactsClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_contacts

    @property
    def human_api_contacts(self):
        if self._human_api_contacts is None:
            from .human_api_contacts.client import HumanApiContactsClient  # noqa: E402

            self._human_api_contacts = HumanApiContactsClient(
                client_wrapper=self._client_wrapper
            )
        return self._human_api_contacts

    @property
    def human_api_memories(self):
        if self._human_api_memories is None:
            from .human_api_memories.client import HumanApiMemoriesClient  # noqa: E402

            self._human_api_memories = HumanApiMemoriesClient(
                client_wrapper=self._client_wrapper
            )
        return self._human_api_memories

    @property
    def human_api_chats(self):
        if self._human_api_chats is None:
            from .human_api_chats.client import HumanApiChatsClient  # noqa: E402

            self._human_api_chats = HumanApiChatsClient(
                client_wrapper=self._client_wrapper
            )
        return self._human_api_chats

    @property
    def agent_api_messages(self):
        if self._agent_api_messages is None:
            from .agent_api_messages.client import AgentApiMessagesClient  # noqa: E402

            self._agent_api_messages = AgentApiMessagesClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_messages

    @property
    def agent_api_memories(self):
        if self._agent_api_memories is None:
            from .agent_api_memories.client import AgentApiMemoriesClient  # noqa: E402

            self._agent_api_memories = AgentApiMemoriesClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_memories

    @property
    def system(self):
        if self._system is None:
            from .system.client import SystemClient  # noqa: E402

            self._system = SystemClient(client_wrapper=self._client_wrapper)
        return self._system

    @property
    def agent_api_peers(self):
        if self._agent_api_peers is None:
            from .agent_api_peers.client import AgentApiPeersClient  # noqa: E402

            self._agent_api_peers = AgentApiPeersClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_peers

    @property
    def human_api_peers(self):
        if self._human_api_peers is None:
            from .human_api_peers.client import HumanApiPeersClient  # noqa: E402

            self._human_api_peers = HumanApiPeersClient(
                client_wrapper=self._client_wrapper
            )
        return self._human_api_peers

    @property
    def human_api_messages(self):
        if self._human_api_messages is None:
            from .human_api_messages.client import HumanApiMessagesClient  # noqa: E402

            self._human_api_messages = HumanApiMessagesClient(
                client_wrapper=self._client_wrapper
            )
        return self._human_api_messages

    @property
    def agent_api_events(self):
        if self._agent_api_events is None:
            from .agent_api_events.client import AgentApiEventsClient  # noqa: E402

            self._agent_api_events = AgentApiEventsClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_events

    @property
    def human_api_agents(self):
        if self._human_api_agents is None:
            from .human_api_agents.client import HumanApiAgentsClient  # noqa: E402

            self._human_api_agents = HumanApiAgentsClient(
                client_wrapper=self._client_wrapper
            )
        return self._human_api_agents

    @property
    def human_api_participants(self):
        if self._human_api_participants is None:
            from .human_api_participants.client import HumanApiParticipantsClient  # noqa: E402

            self._human_api_participants = HumanApiParticipantsClient(
                client_wrapper=self._client_wrapper
            )
        return self._human_api_participants

    @property
    def agent_api_identity(self):
        if self._agent_api_identity is None:
            from .agent_api_identity.client import AgentApiIdentityClient  # noqa: E402

            self._agent_api_identity = AgentApiIdentityClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_identity

    @property
    def agent_api_participants(self):
        if self._agent_api_participants is None:
            from .agent_api_participants.client import AgentApiParticipantsClient  # noqa: E402

            self._agent_api_participants = AgentApiParticipantsClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_participants

    @property
    def agent_api_context(self):
        if self._agent_api_context is None:
            from .agent_api_context.client import AgentApiContextClient  # noqa: E402

            self._agent_api_context = AgentApiContextClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_context

    @property
    def agent_api_chats(self):
        if self._agent_api_chats is None:
            from .agent_api_chats.client import AgentApiChatsClient  # noqa: E402

            self._agent_api_chats = AgentApiChatsClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_chats

    @property
    def test(self):
        if self._test is None:
            from .test.client import TestClient  # noqa: E402

            self._test = TestClient(client_wrapper=self._client_wrapper)
        return self._test

    @property
    def human_api_profile(self):
        if self._human_api_profile is None:
            from .human_api_profile.client import HumanApiProfileClient  # noqa: E402

            self._human_api_profile = HumanApiProfileClient(
                client_wrapper=self._client_wrapper
            )
        return self._human_api_profile


class AsyncRestClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : RestClientEnvironment
        The environment to use for requests from the client. from .environment import RestClientEnvironment



        Defaults to RestClientEnvironment.DEFAULT



    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    from band_rest import AsyncRestClient

    client = AsyncRestClient(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: RestClientEnvironment = RestClientEnvironment.DEFAULT,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
    ):
        _defaulted_timeout = (
            timeout
            if timeout is not None
            else 60
            if httpx_client is None
            else httpx_client.timeout.read
        )
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.AsyncClient(
                timeout=_defaulted_timeout, follow_redirects=follow_redirects
            )
            if follow_redirects is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
        )
        self._agent_api_contacts: typing.Optional[AsyncAgentApiContactsClient] = None
        self._human_api_contacts: typing.Optional[AsyncHumanApiContactsClient] = None
        self._human_api_memories: typing.Optional[AsyncHumanApiMemoriesClient] = None
        self._human_api_chats: typing.Optional[AsyncHumanApiChatsClient] = None
        self._agent_api_messages: typing.Optional[AsyncAgentApiMessagesClient] = None
        self._agent_api_memories: typing.Optional[AsyncAgentApiMemoriesClient] = None
        self._system: typing.Optional[AsyncSystemClient] = None
        self._agent_api_peers: typing.Optional[AsyncAgentApiPeersClient] = None
        self._human_api_peers: typing.Optional[AsyncHumanApiPeersClient] = None
        self._human_api_messages: typing.Optional[AsyncHumanApiMessagesClient] = None
        self._agent_api_events: typing.Optional[AsyncAgentApiEventsClient] = None
        self._human_api_agents: typing.Optional[AsyncHumanApiAgentsClient] = None
        self._human_api_participants: typing.Optional[
            AsyncHumanApiParticipantsClient
        ] = None
        self._agent_api_identity: typing.Optional[AsyncAgentApiIdentityClient] = None
        self._agent_api_participants: typing.Optional[
            AsyncAgentApiParticipantsClient
        ] = None
        self._agent_api_context: typing.Optional[AsyncAgentApiContextClient] = None
        self._agent_api_chats: typing.Optional[AsyncAgentApiChatsClient] = None
        self._test: typing.Optional[AsyncTestClient] = None
        self._human_api_profile: typing.Optional[AsyncHumanApiProfileClient] = None

    @property
    def agent_api_contacts(self):
        if self._agent_api_contacts is None:
            from .agent_api_contacts.client import AsyncAgentApiContactsClient  # noqa: E402

            self._agent_api_contacts = AsyncAgentApiContactsClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_contacts

    @property
    def human_api_contacts(self):
        if self._human_api_contacts is None:
            from .human_api_contacts.client import AsyncHumanApiContactsClient  # noqa: E402

            self._human_api_contacts = AsyncHumanApiContactsClient(
                client_wrapper=self._client_wrapper
            )
        return self._human_api_contacts

    @property
    def human_api_memories(self):
        if self._human_api_memories is None:
            from .human_api_memories.client import AsyncHumanApiMemoriesClient  # noqa: E402

            self._human_api_memories = AsyncHumanApiMemoriesClient(
                client_wrapper=self._client_wrapper
            )
        return self._human_api_memories

    @property
    def human_api_chats(self):
        if self._human_api_chats is None:
            from .human_api_chats.client import AsyncHumanApiChatsClient  # noqa: E402

            self._human_api_chats = AsyncHumanApiChatsClient(
                client_wrapper=self._client_wrapper
            )
        return self._human_api_chats

    @property
    def agent_api_messages(self):
        if self._agent_api_messages is None:
            from .agent_api_messages.client import AsyncAgentApiMessagesClient  # noqa: E402

            self._agent_api_messages = AsyncAgentApiMessagesClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_messages

    @property
    def agent_api_memories(self):
        if self._agent_api_memories is None:
            from .agent_api_memories.client import AsyncAgentApiMemoriesClient  # noqa: E402

            self._agent_api_memories = AsyncAgentApiMemoriesClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_memories

    @property
    def system(self):
        if self._system is None:
            from .system.client import AsyncSystemClient  # noqa: E402

            self._system = AsyncSystemClient(client_wrapper=self._client_wrapper)
        return self._system

    @property
    def agent_api_peers(self):
        if self._agent_api_peers is None:
            from .agent_api_peers.client import AsyncAgentApiPeersClient  # noqa: E402

            self._agent_api_peers = AsyncAgentApiPeersClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_peers

    @property
    def human_api_peers(self):
        if self._human_api_peers is None:
            from .human_api_peers.client import AsyncHumanApiPeersClient  # noqa: E402

            self._human_api_peers = AsyncHumanApiPeersClient(
                client_wrapper=self._client_wrapper
            )
        return self._human_api_peers

    @property
    def human_api_messages(self):
        if self._human_api_messages is None:
            from .human_api_messages.client import AsyncHumanApiMessagesClient  # noqa: E402

            self._human_api_messages = AsyncHumanApiMessagesClient(
                client_wrapper=self._client_wrapper
            )
        return self._human_api_messages

    @property
    def agent_api_events(self):
        if self._agent_api_events is None:
            from .agent_api_events.client import AsyncAgentApiEventsClient  # noqa: E402

            self._agent_api_events = AsyncAgentApiEventsClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_events

    @property
    def human_api_agents(self):
        if self._human_api_agents is None:
            from .human_api_agents.client import AsyncHumanApiAgentsClient  # noqa: E402

            self._human_api_agents = AsyncHumanApiAgentsClient(
                client_wrapper=self._client_wrapper
            )
        return self._human_api_agents

    @property
    def human_api_participants(self):
        if self._human_api_participants is None:
            from .human_api_participants.client import AsyncHumanApiParticipantsClient  # noqa: E402

            self._human_api_participants = AsyncHumanApiParticipantsClient(
                client_wrapper=self._client_wrapper
            )
        return self._human_api_participants

    @property
    def agent_api_identity(self):
        if self._agent_api_identity is None:
            from .agent_api_identity.client import AsyncAgentApiIdentityClient  # noqa: E402

            self._agent_api_identity = AsyncAgentApiIdentityClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_identity

    @property
    def agent_api_participants(self):
        if self._agent_api_participants is None:
            from .agent_api_participants.client import AsyncAgentApiParticipantsClient  # noqa: E402

            self._agent_api_participants = AsyncAgentApiParticipantsClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_participants

    @property
    def agent_api_context(self):
        if self._agent_api_context is None:
            from .agent_api_context.client import AsyncAgentApiContextClient  # noqa: E402

            self._agent_api_context = AsyncAgentApiContextClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_context

    @property
    def agent_api_chats(self):
        if self._agent_api_chats is None:
            from .agent_api_chats.client import AsyncAgentApiChatsClient  # noqa: E402

            self._agent_api_chats = AsyncAgentApiChatsClient(
                client_wrapper=self._client_wrapper
            )
        return self._agent_api_chats

    @property
    def test(self):
        if self._test is None:
            from .test.client import AsyncTestClient  # noqa: E402

            self._test = AsyncTestClient(client_wrapper=self._client_wrapper)
        return self._test

    @property
    def human_api_profile(self):
        if self._human_api_profile is None:
            from .human_api_profile.client import AsyncHumanApiProfileClient  # noqa: E402

            self._human_api_profile = AsyncHumanApiProfileClient(
                client_wrapper=self._client_wrapper
            )
        return self._human_api_profile


def _get_base_url(
    *, base_url: typing.Optional[str] = None, environment: RestClientEnvironment
) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception(
            "Please pass in either base_url or environment to construct the client"
        )
