# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawHumanApiContactsClient, RawHumanApiContactsClient
from .types.approve_contact_request_response import ApproveContactRequestResponse
from .types.cancel_contact_request_response import CancelContactRequestResponse
from .types.create_contact_request_request_contact_request import (
    CreateContactRequestRequestContactRequest,
)
from .types.create_contact_request_response import CreateContactRequestResponse
from .types.list_my_contacts_response import ListMyContactsResponse
from .types.list_received_contact_requests_response import (
    ListReceivedContactRequestsResponse,
)
from .types.list_sent_contact_requests_request_status import (
    ListSentContactRequestsRequestStatus,
)
from .types.list_sent_contact_requests_response import ListSentContactRequestsResponse
from .types.reject_contact_request_response import RejectContactRequestResponse
from .types.remove_my_contact_response import RemoveMyContactResponse
from .types.resolve_handle_response import ResolveHandleResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class HumanApiContactsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawHumanApiContactsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawHumanApiContactsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawHumanApiContactsClient
        """
        return self._raw_client

    def reject_contact_request(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RejectContactRequestResponse:
        """
        Rejects a pending contact request you received.

        The requester will not be notified of the rejection.

        Parameters
        ----------
        id : str
            Contact request ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RejectContactRequestResponse
            Rejected contact request

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_contacts.reject_contact_request(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
        )
        """
        _response = self._raw_client.reject_contact_request(
            id, request_options=request_options
        )
        return _response.data

    def remove_my_contact(
        self,
        *,
        contact_id: typing.Optional[str] = OMIT,
        handle: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RemoveMyContactResponse:
        """
        Removes a contact by handle or contact record ID.

        Note: This removes the contact only from your list. The other party
        will still have you as a contact unless they also remove you.

        Parameters
        ----------
        contact_id : typing.Optional[str]
            Contact record ID

        handle : typing.Optional[str]
            Contact's handle (with or without @ prefix)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RemoveMyContactResponse
            Removed contact

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_contacts.remove_my_contact()
        """
        _response = self._raw_client.remove_my_contact(
            contact_id=contact_id, handle=handle, request_options=request_options
        )
        return _response.data

    def list_received_contact_requests(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListReceivedContactRequestsResponse:
        """
        Returns a paginated list of pending contact requests you have received.

        These are requests from other users who want to add you as a contact.
        You can approve or reject each request.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListReceivedContactRequestsResponse
            Contact requests

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_contacts.list_received_contact_requests(
            page=1,
            page_size=1,
        )
        """
        _response = self._raw_client.list_received_contact_requests(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    def create_contact_request(
        self,
        *,
        contact_request: CreateContactRequestRequestContactRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateContactRequestResponse:
        """
        Sends a contact request to another user.

        You can include an optional message (max 500 characters).
        The recipient will be able to approve or reject the request.

        **Constraints:**
        - Cannot send a request to yourself
        - Cannot send a request if you're already contacts
        - Only one pending request per recipient at a time

        Parameters
        ----------
        contact_request : CreateContactRequestRequestContactRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateContactRequestResponse
            Created contact request

        Examples
        --------
        from band_rest import RestClient
        from band_rest.human_api_contacts import (
            CreateContactRequestRequestContactRequest,
        )

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_contacts.create_contact_request(
            contact_request=CreateContactRequestRequestContactRequest(
                recipient_handle="@johndoe",
            ),
        )
        """
        _response = self._raw_client.create_contact_request(
            contact_request=contact_request, request_options=request_options
        )
        return _response.data

    def list_sent_contact_requests(
        self,
        *,
        status: typing.Optional[ListSentContactRequestsRequestStatus] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListSentContactRequestsResponse:
        """
        Returns a paginated list of contact requests you have sent.

        By default includes all statuses. Use the `status` parameter to filter.
        You can cancel pending requests.

        Parameters
        ----------
        status : typing.Optional[ListSentContactRequestsRequestStatus]
            Filter by status

        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSentContactRequestsResponse
            Sent contact requests

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_contacts.list_sent_contact_requests(
            status="all",
            page=1,
            page_size=1,
        )
        """
        _response = self._raw_client.list_sent_contact_requests(
            status=status,
            page=page,
            page_size=page_size,
            request_options=request_options,
        )
        return _response.data

    def approve_contact_request(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ApproveContactRequestResponse:
        """
        Approves a pending contact request you received.

        This creates a bidirectional contact relationship - both you and the requester
        will be added to each other's contacts.

        Parameters
        ----------
        id : str
            Contact request ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApproveContactRequestResponse
            Approved contact request

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_contacts.approve_contact_request(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
        )
        """
        _response = self._raw_client.approve_contact_request(
            id, request_options=request_options
        )
        return _response.data

    def resolve_handle(
        self, *, handle: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ResolveHandleResponse:
        """
        Resolves a handle (e.g., "@johndoe" or "johndoe") to a user entity.

        Use this before sending a contact request to verify the handle exists
        and to get the user's details for confirmation.

        Parameters
        ----------
        handle : str
            Handle to resolve (with or without @ prefix)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResolveHandleResponse
            Resolved entity

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_contacts.resolve_handle(
            handle="@johndoe",
        )
        """
        _response = self._raw_client.resolve_handle(
            handle=handle, request_options=request_options
        )
        return _response.data

    def cancel_contact_request(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CancelContactRequestResponse:
        """
        Cancels a pending contact request you sent.

        You can only cancel requests that are still pending.

        Parameters
        ----------
        id : str
            Contact request ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelContactRequestResponse
            Cancelled contact request

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_contacts.cancel_contact_request(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
        )
        """
        _response = self._raw_client.cancel_contact_request(
            id, request_options=request_options
        )
        return _response.data

    def list_my_contacts(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMyContactsResponse:
        """
        Returns a paginated list of all your active contacts.

        Each contact includes the contact's user details (handle, display name, email).

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMyContactsResponse
            Contacts

        Examples
        --------
        from band_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.human_api_contacts.list_my_contacts(
            page=1,
            page_size=1,
        )
        """
        _response = self._raw_client.list_my_contacts(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data


class AsyncHumanApiContactsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawHumanApiContactsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawHumanApiContactsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawHumanApiContactsClient
        """
        return self._raw_client

    async def reject_contact_request(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RejectContactRequestResponse:
        """
        Rejects a pending contact request you received.

        The requester will not be notified of the rejection.

        Parameters
        ----------
        id : str
            Contact request ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RejectContactRequestResponse
            Rejected contact request

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_contacts.reject_contact_request(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.reject_contact_request(
            id, request_options=request_options
        )
        return _response.data

    async def remove_my_contact(
        self,
        *,
        contact_id: typing.Optional[str] = OMIT,
        handle: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RemoveMyContactResponse:
        """
        Removes a contact by handle or contact record ID.

        Note: This removes the contact only from your list. The other party
        will still have you as a contact unless they also remove you.

        Parameters
        ----------
        contact_id : typing.Optional[str]
            Contact record ID

        handle : typing.Optional[str]
            Contact's handle (with or without @ prefix)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RemoveMyContactResponse
            Removed contact

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_contacts.remove_my_contact()


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_my_contact(
            contact_id=contact_id, handle=handle, request_options=request_options
        )
        return _response.data

    async def list_received_contact_requests(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListReceivedContactRequestsResponse:
        """
        Returns a paginated list of pending contact requests you have received.

        These are requests from other users who want to add you as a contact.
        You can approve or reject each request.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListReceivedContactRequestsResponse
            Contact requests

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_contacts.list_received_contact_requests(
                page=1,
                page_size=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_received_contact_requests(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def create_contact_request(
        self,
        *,
        contact_request: CreateContactRequestRequestContactRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateContactRequestResponse:
        """
        Sends a contact request to another user.

        You can include an optional message (max 500 characters).
        The recipient will be able to approve or reject the request.

        **Constraints:**
        - Cannot send a request to yourself
        - Cannot send a request if you're already contacts
        - Only one pending request per recipient at a time

        Parameters
        ----------
        contact_request : CreateContactRequestRequestContactRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateContactRequestResponse
            Created contact request

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient
        from band_rest.human_api_contacts import (
            CreateContactRequestRequestContactRequest,
        )

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_contacts.create_contact_request(
                contact_request=CreateContactRequestRequestContactRequest(
                    recipient_handle="@johndoe",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_contact_request(
            contact_request=contact_request, request_options=request_options
        )
        return _response.data

    async def list_sent_contact_requests(
        self,
        *,
        status: typing.Optional[ListSentContactRequestsRequestStatus] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListSentContactRequestsResponse:
        """
        Returns a paginated list of contact requests you have sent.

        By default includes all statuses. Use the `status` parameter to filter.
        You can cancel pending requests.

        Parameters
        ----------
        status : typing.Optional[ListSentContactRequestsRequestStatus]
            Filter by status

        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSentContactRequestsResponse
            Sent contact requests

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_contacts.list_sent_contact_requests(
                status="all",
                page=1,
                page_size=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_sent_contact_requests(
            status=status,
            page=page,
            page_size=page_size,
            request_options=request_options,
        )
        return _response.data

    async def approve_contact_request(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ApproveContactRequestResponse:
        """
        Approves a pending contact request you received.

        This creates a bidirectional contact relationship - both you and the requester
        will be added to each other's contacts.

        Parameters
        ----------
        id : str
            Contact request ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApproveContactRequestResponse
            Approved contact request

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_contacts.approve_contact_request(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.approve_contact_request(
            id, request_options=request_options
        )
        return _response.data

    async def resolve_handle(
        self, *, handle: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ResolveHandleResponse:
        """
        Resolves a handle (e.g., "@johndoe" or "johndoe") to a user entity.

        Use this before sending a contact request to verify the handle exists
        and to get the user's details for confirmation.

        Parameters
        ----------
        handle : str
            Handle to resolve (with or without @ prefix)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResolveHandleResponse
            Resolved entity

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_contacts.resolve_handle(
                handle="@johndoe",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resolve_handle(
            handle=handle, request_options=request_options
        )
        return _response.data

    async def cancel_contact_request(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CancelContactRequestResponse:
        """
        Cancels a pending contact request you sent.

        You can only cancel requests that are still pending.

        Parameters
        ----------
        id : str
            Contact request ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelContactRequestResponse
            Cancelled contact request

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_contacts.cancel_contact_request(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel_contact_request(
            id, request_options=request_options
        )
        return _response.data

    async def list_my_contacts(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMyContactsResponse:
        """
        Returns a paginated list of all your active contacts.

        Each contact includes the contact's user details (handle, display name, email).

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMyContactsResponse
            Contacts

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.human_api_contacts.list_my_contacts(
                page=1,
                page_size=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_my_contacts(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data
