#!/usr/bin/env python3
"""Register the planner + reviewer agents and write agent_config.yaml.

Registers both agents via the Band User API and writes a single combined
``agent_config.yaml`` (keyed ``planner:``/``reviewer:``) — exactly the file
docker-compose.yml consumes. This replaces the old two-step "copy the example,
then paste credentials" flow, which left an empty ``agent_config.yaml``
directory behind (Docker auto-creates the bind-mount source) and crashed both
containers.

Usage:
    BAND_API_KEY=band_u_... python create_agents.py

Optional repo (agents clone + work on a shared git repo). Omit for a
chat-only stack that needs no GitHub/SSH:
    REPO_URL=git@github.com:org/repo.git \
    REPO_BRANCH=main REPO_INDEX=true \
    BAND_API_KEY=band_u_... python create_agents.py

Re-running registers NEW agents. To avoid orphaning the ones already in
agent_config.yaml, the script refuses to overwrite it unless FORCE=1.
"""

from __future__ import annotations

import asyncio
import logging
import os
from pathlib import Path
from typing import Any

import yaml

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

AGENTS = [
    {"name": "Planner", "role": "planner", "key": "planner"},
    {"name": "Reviewer", "role": "reviewer", "key": "reviewer"},
]

SCRIPT_DIR = Path(__file__).resolve().parent
CONFIG_PATH = SCRIPT_DIR / "agent_config.yaml"
CLEANUP_PATH = SCRIPT_DIR / ".agent_ids.txt"

CONFIG_HEADER = """\
# Combined agent credentials for the coding_agents Docker Compose stack.
# Generated by create_agents.py. NEVER commit real credentials.
#
# Keys must match the runner AGENT_KEY:
#   planner  -> AGENT_KEY=planner            (compose service "planner")
#   reviewer -> REVIEWER_AGENT_KEY=reviewer  (compose service "reviewer")
#
# No `repo:` block => the agents boot and coordinate over chat without cloning
# anything (no GitHub/SSH needed). Set REPO_URL when running this script, or add
# an identical `repo:` block under each agent by hand — see
# agent_config.yaml.example for the template.
"""


def build_repo_block() -> dict[str, Any] | None:
    """Build an optional repo block from REPO_* env vars, or None if unset."""
    url = os.environ.get("REPO_URL", "").strip()
    if not url:
        return None

    repo: dict[str, Any] = {
        "url": url,
        "path": os.environ.get("REPO_PATH", "/workspace/repo").strip(),
    }
    branch = os.environ.get("REPO_BRANCH", "").strip()
    if branch:
        repo["branch"] = branch
    repo["index"] = os.environ.get("REPO_INDEX", "true").strip().lower() in (
        "1",
        "true",
        "yes",
    )
    return repo


async def main() -> None:
    api_key = os.environ.get("BAND_API_KEY")
    if not api_key:
        raise ValueError("BAND_API_KEY environment variable is required")

    if CONFIG_PATH.is_file() and os.environ.get("FORCE", "").strip().lower() not in (
        "1",
        "true",
        "yes",
    ):
        raise ValueError(
            f"{CONFIG_PATH.name} already exists. Re-running registers NEW Band "
            "agents and would orphan the ones referenced there. Delete it (and "
            "clean up old agents listed in .agent_ids.txt) or set FORCE=1 to "
            "overwrite."
        )

    base_url = os.environ.get("BAND_REST_URL", "https://app.band.ai")

    from band.client.rest import AsyncRestClient, DEFAULT_REQUEST_OPTIONS
    from band_rest.types import AgentRegisterRequest

    client = AsyncRestClient(api_key=api_key, base_url=base_url)

    repo_block = build_repo_block()
    config: dict[str, Any] = {}
    created: list[dict[str, str]] = []

    for agent_def in AGENTS:
        logger.info("Creating agent: %s ...", agent_def["name"])
        response = await client.human_api_agents.register_my_agent(
            agent=AgentRegisterRequest(
                name=agent_def["name"],
                description=f"coding_agents example - {agent_def['role']} role",
            ),
            request_options=DEFAULT_REQUEST_OPTIONS,
        )

        agent = response.data.agent
        credentials = response.data.credentials
        logger.info("  Created: %s (ID: %s)", agent.name, agent.id)

        # Omit `model` so each runner falls back to its own default (the npm
        # `claude` binary / codex pick their default). Add a `model:` key here
        # to pin one.
        section: dict[str, Any] = {
            "agent_id": agent.id,
            "api_key": credentials.api_key,
            "role": agent_def["role"],
        }
        if repo_block is not None:
            section["repo"] = dict(repo_block)

        config[agent_def["key"]] = section
        created.append({"name": agent.name, "id": agent.id, "role": agent_def["role"]})

    body = yaml.dump(config, default_flow_style=False, sort_keys=False)
    CONFIG_PATH.write_text(f"{CONFIG_HEADER}\n{body}", encoding="utf-8")
    logger.info("\nWrote combined config: %s", CONFIG_PATH.name)

    CLEANUP_PATH.write_text("".join(f"{a['id']}\n" for a in created), encoding="utf-8")
    logger.info("Agent IDs saved to %s for cleanup", CLEANUP_PATH.name)

    logger.info("\n=== Summary ===")
    for a in created:
        logger.info("%s: id=%s, role=%s", a["name"], a["id"], a["role"])
    logger.info(
        "\nRepo: %s", repo_block["url"] if repo_block else "none (chat-only, no clone)"
    )
    logger.info("Registered against: %s", base_url)
    logger.info(
        "IMPORTANT: set BAND_REST_URL in .env to the SAME platform (%s), or the "
        "containers won't find these agents.",
        base_url,
    )
    logger.info("\nNext: docker compose build && docker compose up -d")


if __name__ == "__main__":
    asyncio.run(main())
