#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["band-sdk>=1.2.0,<2.0.0"]
# ///
"""Register the planner + reviewer agents and write agent_config.yaml.

Registers both agents via the Band User API and writes a single combined
``agent_config.yaml`` (keyed ``planner:``/``reviewer:``) — exactly the file
docker-compose.yml consumes. This replaces the old two-step "copy the example,
then paste credentials" flow, which left an empty ``agent_config.yaml``
directory behind (Docker auto-creates the bind-mount source) and crashed both
containers.

Platform selection: the script loads this directory's ``.env`` (the same file
Compose reads), so ``BAND_REST_URL`` there is the single source of truth for
which platform the agents are registered against. Set it once in ``.env``.

Usage:
    BAND_API_KEY=band_u_... uv run create_agents.py

Optional repo (agents clone + work on a shared git repo). Omit for a
chat-only stack that needs no GitHub/SSH:
    REPO_URL=git@github.com:org/repo.git \
    REPO_BRANCH=main REPO_INDEX=true \
    BAND_API_KEY=band_u_... uv run create_agents.py

Re-running registers NEW agents. To avoid orphaning the ones already in
agent_config.yaml, the script refuses to overwrite it unless FORCE=1.
"""

from __future__ import annotations

import asyncio
import logging
import os
from pathlib import Path
from typing import Any

import yaml
from dotenv import load_dotenv

from band import LoggingStyle, LogSettings

# The bare message format only exists for the standard style, so the style is
# pinned rather than read from BAND_LOG_CONSOLE_STYLE.
LogSettings(log_console_style=LoggingStyle.STANDARD).for_application().configure(
    fmt="%(message)s"
)
logger = logging.getLogger(__name__)

AGENTS = [
    {"name": "Planner", "role": "planner", "key": "planner"},
    {"name": "Reviewer", "role": "reviewer", "key": "reviewer"},
]

SCRIPT_DIR = Path(__file__).resolve().parent
ENV_PATH = SCRIPT_DIR / ".env"
CONFIG_PATH = SCRIPT_DIR / "agent_config.yaml"
CLEANUP_PATH = SCRIPT_DIR / ".agent_ids.txt"

CONFIG_HEADER = """\
# Combined agent credentials for the coding_agents Docker Compose stack.
# Generated by create_agents.py. NEVER commit real credentials.
#
# Keys must match the runner AGENT_KEY:
#   planner  -> AGENT_KEY=planner            (compose service "planner")
#   reviewer -> REVIEWER_AGENT_KEY=reviewer  (compose service "reviewer")
#
# No `repo:` block => the agents boot and coordinate over chat without cloning
# anything (no GitHub/SSH needed). Set REPO_URL when running this script, or add
# an identical `repo:` block under each agent by hand — see
# agent_config.yaml.example for the template.
"""


def env_flag(name: str, *, default: bool = False) -> bool:
    """Read a truthy env flag (``1``/``true``/``yes``), or *default* if unset."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ("1", "true", "yes")


def build_repo_block() -> dict[str, Any] | None:
    """Build an optional repo block from REPO_* env vars, or None if unset."""
    url = os.environ.get("REPO_URL", "").strip()
    if not url:
        return None

    repo: dict[str, Any] = {
        "url": url,
        "path": os.environ.get("REPO_PATH", "/workspace/repo").strip(),
    }
    branch = os.environ.get("REPO_BRANCH", "").strip()
    if branch:
        repo["branch"] = branch
    repo["index"] = env_flag("REPO_INDEX", default=True)
    return repo


def config_write_blocked_reason() -> str | None:
    """Explain why ``agent_config.yaml`` can't be safely written, else ``None``.

    Called BEFORE any agent is registered, so we never create agents we then
    can't record. ``is_file()`` is deliberately avoided: it returns ``False``
    for a stale ``agent_config.yaml`` *directory* (Docker auto-creates the
    bind-mount source as one when the file is missing — the exact state this
    stack recovers from), which would let registration run and only crash later
    at ``write_text``.
    """
    if CONFIG_PATH.is_dir():
        return (
            f"{CONFIG_PATH.name} is a directory. Docker auto-creates the bind-mount "
            "source as an empty directory when the file is missing — the exact state "
            "this stack must recover from. Run `docker compose down`, then "
            f"`rm -rf {CONFIG_PATH.name}` and re-run this script."
        )
    if CONFIG_PATH.exists() and not env_flag("FORCE"):
        return (
            f"{CONFIG_PATH.name} already exists. Re-running registers NEW Band agents "
            "and would orphan the ones referenced there. Delete it (and clean up the "
            f"agents listed in {CLEANUP_PATH.name}), or set FORCE=1 to overwrite."
        )
    return None


def append_cleanup_id(agent_id: str) -> None:
    """Append a freshly registered agent id to the cleanup ledger immediately.

    Written per-agent (append, not overwrite) so a failure part-way through
    registration — or a FORCE re-run — never orphans an already-created agent:
    every id ever registered stays recorded for teardown.
    """
    with open(CLEANUP_PATH, "a", encoding="utf-8") as f:
        f.write(f"{agent_id}\n")


def write_config(config: dict[str, Any]) -> None:
    """Write the combined, keyed ``agent_config.yaml`` that Compose consumes."""
    body = yaml.dump(config, default_flow_style=False, sort_keys=False)
    CONFIG_PATH.write_text(f"{CONFIG_HEADER}\n{body}", encoding="utf-8")
    logger.info("\nWrote combined config: %s", CONFIG_PATH.name)


def log_summary(
    created: list[dict[str, str]],
    repo_block: dict[str, Any] | None,
    base_url: str,
) -> None:
    """Print the registration summary and the next-step setup instructions."""
    logger.info("Agent IDs recorded in %s for cleanup", CLEANUP_PATH.name)
    logger.info("\n=== Summary ===")
    for a in created:
        logger.info("%s: id=%s, role=%s", a["name"], a["id"], a["role"])
    logger.info(
        "\nRepo: %s", repo_block["url"] if repo_block else "none (chat-only, no clone)"
    )
    logger.info("Registered against: %s", base_url)
    logger.info(
        "IMPORTANT: BAND_REST_URL in .env (%s) is the platform these agents live on; "
        "the containers must use the same one to find them.",
        base_url,
    )
    logger.info("\nNext: docker compose build && docker compose up -d")


async def main() -> None:
    # Load this directory's .env first, so BAND_REST_URL matches the platform
    # Compose connects to (Compose reads the same .env via env_file).
    load_dotenv(ENV_PATH)

    api_key = os.environ.get("BAND_API_KEY")
    if not api_key:
        raise ValueError("BAND_API_KEY environment variable is required")

    blocked = config_write_blocked_reason()
    if blocked:
        raise ValueError(blocked)

    base_url = os.environ.get("BAND_REST_URL", "https://app.band.ai")

    from band.client.rest import AsyncRestClient, DEFAULT_REQUEST_OPTIONS
    from band_rest.types import AgentRegisterRequest

    client = AsyncRestClient(api_key=api_key, base_url=base_url)

    repo_block = build_repo_block()
    config: dict[str, Any] = {}
    created: list[dict[str, str]] = []

    for agent_def in AGENTS:
        logger.info("Creating agent: %s ...", agent_def["name"])
        response = await client.human_api_agents.register_my_agent(
            agent=AgentRegisterRequest(
                name=agent_def["name"],
                description=f"coding_agents example - {agent_def['role']} role",
            ),
            request_options=DEFAULT_REQUEST_OPTIONS,
        )

        agent = response.data.agent
        credentials = response.data.credentials
        # Persist the id before anything else can fail (a later agent's
        # registration, or the config write): a partial run stays cleanable.
        append_cleanup_id(agent.id)
        logger.info("  Created: %s (ID: %s)", agent.name, agent.id)

        # Omit `model` so each runner falls back to its own default (the npm
        # `claude` binary / codex pick their default). Add a `model:` key here
        # to pin one.
        section: dict[str, Any] = {
            "agent_id": agent.id,
            "api_key": credentials.api_key,
            "role": agent_def["role"],
        }
        if repo_block is not None:
            section["repo"] = dict(repo_block)

        config[agent_def["key"]] = section
        created.append({"name": agent.name, "id": agent.id, "role": agent_def["role"]})

    write_config(config)
    log_summary(created, repo_block, base_url)


if __name__ == "__main__":
    asyncio.run(main())
