# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.datetime_utils import serialize_datetime
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.chat_message_request import ChatMessageRequest
from ..types.error import Error
from .types.list_my_chat_messages_request_message_type import (
    ListMyChatMessagesRequestMessageType,
)
from .types.list_my_chat_messages_response import ListMyChatMessagesResponse
from .types.send_my_chat_message_response import SendMyChatMessageResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawHumanApiMessagesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_my_chat_messages(
        self,
        chat_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        message_type: typing.Optional[ListMyChatMessagesRequestMessageType] = None,
        since: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListMyChatMessagesResponse]:
        """
        Returns a paginated list of ALL messages in a chat room where you are a participant.

        This includes all message types: text, tool_call, tool_result, thought, error.
        Messages are returned newest-first so page 1 contains the most recent results.
        Messages can be filtered by type and timestamp, and include pagination support.

        Use the `message_type` parameter to filter by specific type(s).

        Returns 404 if the chat room doesn't exist or you're not a participant (security-first: doesn't leak room existence).

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page

        message_type : typing.Optional[ListMyChatMessagesRequestMessageType]
            Filter by message type (text, tool_call, tool_result, thought, error)

        since : typing.Optional[dt.datetime]
            Filter messages after this timestamp

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListMyChatMessagesResponse]
            Chat Messages
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/me/chats/{jsonable_encoder(chat_id)}/messages",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
                "message_type": message_type,
                "since": serialize_datetime(since) if since is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListMyChatMessagesResponse,
                    parse_obj_as(
                        type_=ListMyChatMessagesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )

    def send_my_chat_message(
        self,
        chat_id: str,
        *,
        message: ChatMessageRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SendMyChatMessageResponse]:
        """
        Creates a new text message in a chat room. The user must be a participant in the room.

        This endpoint only supports `text` message type. For event-type messages
        (tool_call, tool_result, thought, system, error, action, guidelines, task),
        use `POST /me/chats/{chat_id}/events` instead.

        Messages must include at least one @mention to ensure proper routing to recipients.

        Example request:
        ```json
        {
          "message": {
            "content": "@agent.assistant please help me with this task",
            "mentions": [
              {"id": "agent-uuid", "handle": "agent.assistant", "name": "Agent Assistant"}
            ]
          }
        }
        ```

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        message : ChatMessageRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SendMyChatMessageResponse]
            Message Sent
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/me/chats/{jsonable_encoder(chat_id)}/messages",
            method="POST",
            json={
                "message": convert_and_respect_annotation_metadata(
                    object_=message, annotation=ChatMessageRequest, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SendMyChatMessageResponse,
                    parse_obj_as(
                        type_=SendMyChatMessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )


class AsyncRawHumanApiMessagesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_my_chat_messages(
        self,
        chat_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        message_type: typing.Optional[ListMyChatMessagesRequestMessageType] = None,
        since: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListMyChatMessagesResponse]:
        """
        Returns a paginated list of ALL messages in a chat room where you are a participant.

        This includes all message types: text, tool_call, tool_result, thought, error.
        Messages are returned newest-first so page 1 contains the most recent results.
        Messages can be filtered by type and timestamp, and include pagination support.

        Use the `message_type` parameter to filter by specific type(s).

        Returns 404 if the chat room doesn't exist or you're not a participant (security-first: doesn't leak room existence).

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Items per page

        message_type : typing.Optional[ListMyChatMessagesRequestMessageType]
            Filter by message type (text, tool_call, tool_result, thought, error)

        since : typing.Optional[dt.datetime]
            Filter messages after this timestamp

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListMyChatMessagesResponse]
            Chat Messages
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/me/chats/{jsonable_encoder(chat_id)}/messages",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
                "message_type": message_type,
                "since": serialize_datetime(since) if since is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListMyChatMessagesResponse,
                    parse_obj_as(
                        type_=ListMyChatMessagesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )

    async def send_my_chat_message(
        self,
        chat_id: str,
        *,
        message: ChatMessageRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SendMyChatMessageResponse]:
        """
        Creates a new text message in a chat room. The user must be a participant in the room.

        This endpoint only supports `text` message type. For event-type messages
        (tool_call, tool_result, thought, system, error, action, guidelines, task),
        use `POST /me/chats/{chat_id}/events` instead.

        Messages must include at least one @mention to ensure proper routing to recipients.

        Example request:
        ```json
        {
          "message": {
            "content": "@agent.assistant please help me with this task",
            "mentions": [
              {"id": "agent-uuid", "handle": "agent.assistant", "name": "Agent Assistant"}
            ]
          }
        }
        ```

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        message : ChatMessageRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SendMyChatMessageResponse]
            Message Sent
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/me/chats/{jsonable_encoder(chat_id)}/messages",
            method="POST",
            json={
                "message": convert_and_respect_annotation_metadata(
                    object_=message, annotation=ChatMessageRequest, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SendMyChatMessageResponse,
                    parse_obj_as(
                        type_=SendMyChatMessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(
                status_code=_response.status_code,
                headers=dict(_response.headers),
                body=_response.text,
            )
        raise ApiError(
            status_code=_response.status_code,
            headers=dict(_response.headers),
            body=_response_json,
        )
