# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.chat_event_request import ChatEventRequest
from .raw_client import AsyncRawAgentApiEventsClient, RawAgentApiEventsClient
from .types.create_agent_chat_event_response import CreateAgentChatEventResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentApiEventsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentApiEventsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentApiEventsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentApiEventsClient
        """
        return self._raw_client

    def create_agent_chat_event(
        self,
        chat_id: str,
        *,
        event: ChatEventRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateAgentChatEventResponse:
        """
        Creates a new event in a chat room.

        Events do NOT require mentions - they report what happened rather than directing messages
        at participants. Use this endpoint to record:

        - **tool_call**: When the agent invokes a tool
        - **tool_result**: The result returned from a tool execution
        - **thought**: Agent's internal reasoning or thinking process
        - **error**: Error messages and failure notifications
        - **task**: Task-related messages

        For text messages with mentions, use POST /agent/chats/{chat_id}/messages instead.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        event : ChatEventRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAgentChatEventResponse
            Event created

        Examples
        --------
        from band_rest import ChatEventRequest, RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agent_api_events.create_agent_chat_event(
            chat_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            event=ChatEventRequest(
                content="Calling send_direct_message_service",
                message_type="tool_call",
            ),
        )
        """
        _response = self._raw_client.create_agent_chat_event(
            chat_id, event=event, request_options=request_options
        )
        return _response.data


class AsyncAgentApiEventsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentApiEventsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentApiEventsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentApiEventsClient
        """
        return self._raw_client

    async def create_agent_chat_event(
        self,
        chat_id: str,
        *,
        event: ChatEventRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateAgentChatEventResponse:
        """
        Creates a new event in a chat room.

        Events do NOT require mentions - they report what happened rather than directing messages
        at participants. Use this endpoint to record:

        - **tool_call**: When the agent invokes a tool
        - **tool_result**: The result returned from a tool execution
        - **thought**: Agent's internal reasoning or thinking process
        - **error**: Error messages and failure notifications
        - **task**: Task-related messages

        For text messages with mentions, use POST /agent/chats/{chat_id}/messages instead.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        event : ChatEventRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAgentChatEventResponse
            Event created

        Examples
        --------
        import asyncio

        from band_rest import AsyncRestClient, ChatEventRequest

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_api_events.create_agent_chat_event(
                chat_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
                event=ChatEventRequest(
                    content="Calling send_direct_message_service",
                    message_type="tool_call",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_agent_chat_event(
            chat_id, event=event, request_options=request_options
        )
        return _response.data
